version: "3.2"
secrets:
  CREDENTIALS_FILE:
    file: ${HOME}/credentials

services:
  shell:
    build:
      context: .
      dockerfile: docker/ingest/Dockerfile
      target: prod
    volumes:
      - ${data}:/opt/data
      - ${public}:/public
    secrets:
      - CREDENTIALS_FILE
    environment:
    - CREDENTIALS=/run/secrets/CREDENTIALS_FILE
    command: /bin/bash
  test:
    build:
      context: .
      dockerfile: docker/ingest/Dockerfile
      target: dev
    volumes:
      -  ${data}:/opt/data
    secrets:
      - CREDENTIALS_FILE
    environment:
    - CREDENTIALS=/run/secrets/CREDENTIALS_FILE
    command: poetry run pytest tests
  # FIXME - add a way to specify unit & integration tests
  ingest:
    build:
      context: .
      dockerfile: docker/ingest/Dockerfile
      target: prod
    volumes:
      - ${data}:/opt/data
      - ${public}:/public
    secrets:
      - CREDENTIALS_FILE
    command:
      - "--credentials_file=/run/secrets/CREDENTIALS_FILE"
      - "--output_dir=/opt/data/test/outdir"
      - "--log_dir=/opt/data/test/logs"
      - "--metrics_dir=/opt/data/test/metrics"
      - "--transfer_dir=/opt/data/test/xfer"
  import:
    build:
      context: .
      dockerfile: docker/import/Dockerfile
    volumes:
      - ${data}:/opt/data
    secrets:
      - CREDENTIALS_FILE
    command:
      - "-c /run/secrets/CREDENTIALS_FILE"
      - "-l /opt/data/xfer"
      - "-t /opt/data/temp_tar"
      - "-m /opt/data/common/job_metrics"
