x-ingest-image: &ingest-image
  build:
    context: .
    dockerfile: docker/ingest/Dockerfile
    args:
      BUILDVER: ${BUILDVER:-dev}
      COMMITBRANCH: ${COMMITBRANCH:-local}
      COMMITSHA: ${COMMITSHA:-dirty}
  image: vxingest/ingest:${BUILDVER:-dev}

x-import-image: &import-image
  platform: linux/amd64
  build:
    context: .
    dockerfile: docker/import/Dockerfile
    args:
      BUILDVER: ${BUILDVER:-dev}
      COMMITBRANCH: ${COMMITBRANCH:-local}
      COMMITSHA: ${COMMITSHA:-dirty}
  image: vxingest/import:${BUILDVER:-dev}

secrets:
  CREDENTIALS_FILE:
    file: ${CREDENTIALS_FILE:-${HOME}/credentials}

services:
  shell:
    <<: *ingest-image
    volumes:
      - ${data:-./tmp/data}:/opt/data
      - ${public:-./tmp/public}:/public
    secrets:
      - CREDENTIALS_FILE
    environment:
    - CREDENTIALS=/run/secrets/CREDENTIALS_FILE
    entrypoint: /bin/bash
  test:
    build: # build the image so we can specify the target
      context: .
      dockerfile: docker/ingest/Dockerfile
      target: dev
    volumes:
      -  ${data:-./tmp/data}:/opt/data
    secrets:
      - CREDENTIALS_FILE
    environment:
    - CREDENTIALS=/run/secrets/CREDENTIALS_FILE
    command: uv run pytest tests
  # FIXME - add a way to specify unit & integration tests
  ingest:
    <<: *ingest-image
    volumes:
      - ${data:-./tmp/data}:/opt/data
      - ${public:-./tmp/public}:/public
    secrets:
      - CREDENTIALS_FILE
    command:
      - "--credentials_file=/run/secrets/CREDENTIALS_FILE"
      - "--output_dir=/opt/data/outdir"
      - "--log_dir=/opt/data/logs"
      - "--metrics_dir=/opt/data/metrics"
      - "--transfer_dir=/opt/data/xfer"
  import:
    <<: *import-image
    volumes:
      - ${data:-./tmp/data}:/opt/data_import
    secrets:
      - CREDENTIALS_FILE
    command:
      - "-c /run/secrets/CREDENTIALS_FILE"
      - "-l /opt/data_import/load_dir"
      - "-t /opt/data_import/temp_tar"
