secrets:
  CREDENTIALS_FILE:
    file: ${CREDENTIALS_FILE:-${HOME}/credentials}
  CACERT_FILE:
    file: ${CACERT_FILE:-${HOME}/cacert.pem}

services:
  shell:
    image: ghcr.io/noaa-gsl/vxingest/ingest:main
    volumes:
      - ${data:-./tmp/data}:/opt/data
      - ${public:-./tmp/public}:/public
    secrets:
      - CREDENTIALS_FILE
      - CACERT_FILE
    environment:
      CREDENTIALS: /run/secrets/CREDENTIALS_FILE
      CACERT_FILE: /run/secrets/CACERT_FILE
    entrypoint: /bin/bash

  test:
    build: # build the image so we can specify the target
      context: .
      dockerfile: docker/ingest/Dockerfile
      target: dev
    volumes:
      -  ${data:-./tmp/data}:/opt/data
    secrets:
      - CREDENTIALS_FILE
    environment:
      CREDENTIALS: /run/secrets/CREDENTIALS_FILE
    command: uv run pytest tests
  # FIXME - add a way to specify unit & integration tests
  ingest:
    # NOTE: --job_id (-j) is required and must be supplied at runtime:
    # docker compose run ingest -j JOB-TEST:V01:METAR:NETCDF:OBS
    #image: ghcr.io/noaa-gsl/vxingest/ingest:main
    image: vxingest/ingest:dev
    volumes:
      - ${data:-./tmp/data}:/opt/data
      - ${public:-./tmp/public}:/public
    secrets:
      - CREDENTIALS_FILE
    command:
      - "--credentials_file=/run/secrets/CREDENTIALS_FILE"
      - "--output_dir=/opt/data/test/outdir"
      - "--log_dir=/opt/data/test/logs"
      - "--metrics_dir=/opt/data/test/metrics"
      - "--transfer_dir=/opt/data/test/xfer"
