# For a list of available rules, see: https://docs.astral.sh/ruff/rules/
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "UP", # pyupgrade
    "I", # isort
    "PTH", # flake8-use-pathlib
    "PT", # flake8-pytest-style
    "B", # bugbear
]

ignore = [
    "E501", # Supress line-too-long warnings: trust the formatter's judgement on this one.
    "W505", # Supress line-too-long warnings: trust the formatter's judgement on this one.
]