"""Unit tests for cfgrib/xarray GRIB2 loading.

These tests exercise the exact xr.open_dataset() calls and variable
extraction patterns used in grib_builder_parent.build_document(),
using a synthetic GRIB2 file generated by the ``synthetic_grib2``
fixture (see conftest.py).

Purpose: catch regressions in the cfgrib / eccodes / eccodeslib
dependency chain — the same class of bug that motivated adding
the eccodeslib workaround pin in pyproject.toml.

No Couchbase connection or external data files required.
"""

from pathlib import Path

import numpy as np
import xarray as xr

from .conftest import FILL_VALUE, GRID_PARAMS, STEP_HOURS

# -- heightAboveGround level 2 ------------------------------------------------


def test_open_height_above_ground_2m(synthetic_grib2: Path):
    """xr.open_dataset with filter_by_keys for heightAboveGround level 2
    returns a dataset containing the expected 2-m variables."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {
                "typeOfLevel": "heightAboveGround",
                "stepType": "instant",
                "level": 2,
            },
            "read_keys": ["projString"],
            "indexpath": "",
        },
    )

    expected_long_names = {
        "2 metre temperature",
        "2 metre dewpoint temperature",
        "2 metre relative humidity",
        "2 metre specific humidity",
    }
    actual_long_names = {ds[v].attrs["long_name"] for v in ds.data_vars}
    assert expected_long_names == actual_long_names


def test_filter_by_attrs_2m_temperature(synthetic_grib2: Path):
    """filter_by_attrs(long_name=...) returns a non-empty dataset whose
    first data variable has a numpy array of the expected shape — this
    is the exact access pattern used in build_document()."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {
                "typeOfLevel": "heightAboveGround",
                "stepType": "instant",
                "level": 2,
            },
            "read_keys": ["projString"],
            "indexpath": "",
        },
    )
    filtered = ds.filter_by_attrs(long_name="2 metre temperature")
    assert len(filtered.data_vars) > 0

    var_name = list(filtered.data_vars.keys())[0]
    values = filtered.variables[var_name].values
    assert isinstance(values, np.ndarray)
    assert values.shape == (GRID_PARAMS["Ny"], GRID_PARAMS["Nx"])


# -- heightAboveGround level 10 -----------------------------------------------


def test_open_height_above_ground_10m(synthetic_grib2: Path):
    """heightAboveGround level 10 dataset contains U and V wind components."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {
                "typeOfLevel": "heightAboveGround",
                "stepType": "instant",
                "level": 10,
            },
            "indexpath": "",
        },
    )

    actual_long_names = {ds[v].attrs["long_name"] for v in ds.data_vars}
    assert "10 metre U wind component" in actual_long_names
    assert "10 metre V wind component" in actual_long_names


# -- surface -------------------------------------------------------------------


def test_open_surface(synthetic_grib2: Path):
    """Surface-level dataset contains pressure, orography, visibility,
    and vegetation variables."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {"typeOfLevel": "surface", "stepType": "instant"},
            "read_keys": ["projString"],
            "indexpath": "",
        },
    )

    actual_long_names = {ds[v].attrs["long_name"] for v in ds.data_vars}
    assert "Surface pressure" in actual_long_names
    assert "Orography" in actual_long_names
    assert "Visibility" in actual_long_names


# -- cloudCeiling --------------------------------------------------------------


def test_open_cloud_ceiling(synthetic_grib2: Path):
    """cloudCeiling dataset has at least one data variable."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {
                "typeOfLevel": "cloudCeiling",
                "stepType": "instant",
            },
            "indexpath": "",
        },
    )
    assert len(ds.data_vars) > 0


# -- meanSea -------------------------------------------------------------------


def test_open_mean_sea_level(synthetic_grib2: Path):
    """meanSea dataset has at least one data variable."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {"typeOfLevel": "meanSea", "stepType": "instant"},
            "read_keys": ["projString"],
            "indexpath": "",
        },
    )
    assert len(ds.data_vars) > 0


# -- projection metadata ------------------------------------------------------


def test_proj_string_accessible(synthetic_grib2: Path):
    """GRIB_projString attribute is accessible via read_keys and contains
    Lambert Conformal Conic parameters."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {
                "typeOfLevel": "heightAboveGround",
                "stepType": "instant",
                "level": 2,
            },
            "read_keys": ["projString"],
            "indexpath": "",
        },
    )
    first_var = list(ds.data_vars)[0]
    proj_string = ds[first_var].attrs["GRIB_projString"]
    assert "+proj=lcc" in proj_string


def test_grid_dimensions(synthetic_grib2: Path):
    """GRIB_Nx, GRIB_Ny, and GRIB_DxInMetres attributes match the
    values used to generate the synthetic file."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {
                "typeOfLevel": "heightAboveGround",
                "stepType": "instant",
                "level": 2,
            },
            "read_keys": ["projString"],
            "indexpath": "",
        },
    )
    first_var = list(ds.data_vars)[0]
    assert ds[first_var].attrs["GRIB_Nx"] == GRID_PARAMS["Nx"]
    assert ds[first_var].attrs["GRIB_Ny"] == GRID_PARAMS["Ny"]
    assert ds[first_var].attrs["GRIB_DxInMetres"] == GRID_PARAMS["DxInMetres"]


# -- time metadata -------------------------------------------------------------


def test_valid_time_and_step(synthetic_grib2: Path):
    """valid_time and step coordinates are present and the epoch
    conversion used in build_document() produces a plausible value."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {
                "typeOfLevel": "heightAboveGround",
                "stepType": "instant",
                "level": 2,
            },
            "indexpath": "",
        },
    )

    # Epoch conversion — mirrors grib_builder_parent.build_document()
    fcst_valid_epoch = (
        ds.valid_time.values.astype("uint64") / 10**9
    ).astype("uint32")
    assert fcst_valid_epoch > 0

    # Step conversion — mirrors build_document()
    fcst_len = int(ds.step.values / 1e9 / 3600)
    assert fcst_len == STEP_HOURS


# -- data values ---------------------------------------------------------------


def test_data_values_shape_and_content(synthetic_grib2: Path):
    """Data values are accessible as numpy arrays with the expected
    grid shape and (approximately) the fill value used during generation."""
    ds = xr.open_dataset(
        synthetic_grib2,
        engine="cfgrib",
        backend_kwargs={
            "filter_by_keys": {
                "typeOfLevel": "heightAboveGround",
                "stepType": "instant",
                "level": 2,
            },
            "indexpath": "",
        },
    )
    for var_name in ds.data_vars:
        values = ds.variables[var_name].values
        assert values.shape == (GRID_PARAMS["Ny"], GRID_PARAMS["Nx"])
        assert np.allclose(values, FILL_VALUE, atol=0.1)
