'\" t
.\"     Title: cbbackupmgr-help
.\"    Author: Couchbase
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2023-09-20
.\"    Manual: Couchbase Server Manual
.\"    Source: Couchbase Server 7.2.2-6401
.\"  Language: English
.\"
.TH "CBBACKUPMGR\-HELP" "1" "2023-09-20" "Couchbase Server 7.2.2\-6401" "Couchbase Server Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
cbbackupmgr-help \- Shows cbbackupmgr documentation
.SH "SYNOPSIS"
.sp
.nf
cbbackupmgr help <page>
.fi
.br
.SH "DESCRIPTION"
.sp
Show documentation about cbbackupmgr. You can look up documentation by command
name or page name.
.SH "EXAMPLES"
.sp
The help command can be used to show various kinds of documentation. Below are
some examples of how to view documentation for subcommands, tutorials, and other
pages. To show the help page for the \fBcbbackupmgr\-config\fP(1) command you
would run the following command:
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr help config
.fam
.fi
.if n .RE
.sp
To show the cbbackupmgr\-tutorial page you would run the following command:
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr help tutorial
.fam
.fi
.if n .RE
.sp
To show  the cbbackupmgr\-strategies page you would run the following command:
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr help strategies
.fam
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fBcbbackupmgr\-config\fP(1),
\fBcbbackupmgr\-tutorial\fP(7),
\fBcbbackupmgr\-strategies\fP(7)
.SH "CBBACKUPMGR"
.sp
Part of the \fBcbbackupmgr\fP(1) suite
.SH "AUTHOR"
.sp
Couchbase