'\" t
.\"     Title: cbbackupmgr-compact
.\"    Author: Couchbase
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2023-09-20
.\"    Manual: Couchbase Server Manual
.\"    Source: Couchbase Server 7.2.2-6401
.\"  Language: English
.\"
.TH "CBBACKUPMGR\-COMPACT" "1" "2023-09-20" "Couchbase Server 7.2.2\-6401" "Couchbase Server Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
cbbackupmgr-compact \- Compacts a backup to free disk space
.SH "SYNOPSIS"
.sp
.nf
cbbackupmgr compact [\-\-archive <archive_dir>] [\-\-repo <repo_name>]
                    [\-\-backup <backup_name>]
.fi
.br
.SH "DESCRIPTION"
.sp
Compacting backups created with a 6.6.0+ version of \f(CRcbbackupmgr\fP is no longer
supported/required due to changes in the storage format which significantly
reduced backup fragmentation.
.sp
Compacts a backup in a backup repository in order to free up disk space. Should
be run on each backup after it completes. The amount of freed disk space is
displayed when the compaction completes.
.SH "OPTIONS"
.sp
Below are a list of parameters for the compact command.
.SS "Required"
.sp
\-a,\-\-archive <archive_dir>
.RS 4
The location of the archive directory.
.RE
.sp
\-r,\-\-repo <repo_name>
.RS 4
The name of the backup repository where the backup to be compacted is
located.
.RE
.sp
\-\-backup <backup_name>
.RS 4
The name of the backup in the backup repository to compact or an index
value which references an incremental backup to compact. Valid index values
are any positive integer, "oldest", and "latest". If a positive integer is
used then it should reference the index of the incremental backup to compact
starting from the oldest to the most recent backup. For example, "1"
corresponds to the oldest backup, "2" corresponds to the second oldest backup,
and so on. Specifying "oldest" means that the index of the oldest backup
should be used and specifying "latest" means the index of the most recent
backup should be used.
.RE
.sp
\-t,\-\-threads <num>
.RS 4
Specify the number of files to be compacted in parallel. By default it is set
to 1, but it is recommended to set to match the number of CPUs in the system
although it can vary depending on the available RAM.
.RE
.SH "EXAMPLES"
.sp
The compact command is used to compact backups in order to free disk space and
should be run after each backup. Below is an example of how to run the
compaction command. The /data/backup directory is used as the archive directory
and the backup repository is named "example".
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr config \-a /data/backup \-r example
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr backup \-a /data/backup \-r example \(rs
 \-c 127.0.0.1:8091 \-u Administrator \-p password
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr compact \-a /data/backup \-r example \(rs
 \-\-backup 2016\-02\-12T12_45_33.329408761\-08_00
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
Compaction succeeded, 58589184 bytes freed
.fam
.fi
.if n .RE
.SH "DISCUSSION"
.sp
The compact command can be run after a backup to reclaim any fragmented disk
space in the backup data files. It should be noted however that compaction may
be run during the backup itself if the fragmentation in the data file begins to
grow too big. Although the compaction can run during the backup it is not
guaranteed to be run once the backup has completed, hence the reason for the
compact command.
.SH "ENVIRONMENT AND CONFIGURATION VARIABLES"
.sp
CB_ARCHIVE_PATH
.RS 4
Specifies the path to the backup archive. If the archive path is supplied as
a command line argument then this value is overridden.
.RE
.SH "FILES"
.sp
shard\-*.fdb
.RS 4
The compact command will compact all shard\-*.fdb files in the backup
specified by the compact command.
.RE
.SH "SEE ALSO"
.sp
\fBcbbackupmgr\-backup\fP(1),
\fBcbbackupmgr\-info\fP(1),
\fBcbbackupmgr\-strategies\fP(1)
.SH "CBBACKUPMGR"
.sp
Part of the \fBcbbackupmgr\fP(1) suite
.SH "AUTHOR"
.sp
Couchbase