'\" t
.\"     Title: cbbackupmgr-remove
.\"    Author: Couchbase
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2023-09-20
.\"    Manual: Couchbase Server Manual
.\"    Source: Couchbase Server 7.2.2-6401
.\"  Language: English
.\"
.TH "CBBACKUPMGR\-REMOVE" "1" "2023-09-20" "Couchbase Server 7.2.2\-6401" "Couchbase Server Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
cbbackupmgr-remove \- Removes a backup repository from the backup archive
.SH "SYNOPSIS"
.sp
.nf
cbbackupmgr remove [\-\-archive <archive_dir>] [\-\-repo <repo_name>]
                   [\-\-backups <backup_range>] [\-\-obj\-access\-key\-id <access_key_id>]
                   [\-\-obj\-cacert <cert_path>] [\-\-obj\-endpoint <endpoint>]
                   [\-\-obj\-no\-ssl\-verify] [\-\-obj\-region <region>]
                   [\-\-obj\-staging\-dir <staging_dir>]
                   [\-\-obj\-secret\-access\-key <secret_access_key>]
                   [\-\-s3\-force\-path\-style] [\-\-s3\-log\-level <level>]
.fi
.br
.SH "DESCRIPTION"
.sp
Removes a backup repository from the backup archive. All contents of the
specified repository will be deleted from disk.
.SH "OPTIONS"
.sp
Below are a list of parameters for the remove command.
.sp
\-a,\-\-archive <archive_dir>
.RS 4
The location of the archive directory. If the archive is stored in S3 prefix
the archive path with \f(CRs3://${BUCKET_NAME}/\fP.
.RE
.sp
\-r,\-\-repo <repo_name>
.RS 4
The name of the backup repository to remove.
.RE
.SS "Optional"
.sp
\-\-start <start>
.RS 4
The first backup to remove. See START AND END for information on what values
are accepted.
.RE
.sp
\-\-end <end>
.RS 4
The final backup to remove. See START AND END for information on what values
are accepted.
.RE
.sp
\-\-backups <backup_range>
.RS 4
This flag will accept either a single backup directory
(e.g. \f(CR\-\-backups 2019\-08\-23T09_36_56.957232625Z\fP) a comma separated range in
the same formats as \f(CR\-\-start\fP and \f(CR\-\-end\fP. See START AND END section for more
information on the accepted formats.
.RE
.SS "Cloud integration"
.sp
Native cloud integration is an Enterprise Edition feature which was introduced
in Couchbase Server 6.6.0.
.sp
Multiple cloud providers are supported, see the list below for more information.
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Supported
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
AWS S3 (\f(CRs3://\fP)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
GCP Google Storage (\f(CRgs://\fP)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Azure Blob Storage in 7.1.2+ (\f(CRaz://\fP)
.RE
.RE
.SS "Required"
.sp
\-\-obj\-staging\-dir <staging_dir>
.RS 4
When performing an operation on an archive which is located in the cloud such
as AWS, the staging directory is used to store local meta data files. This
directory can be temporary (it\(cqs not treated as a persistent store) and is
only used during the backup. NOTE: Do not use \f(CR/tmp\fP as the \f(CRobj\-staging\-dir\fP.
See \f(CRDisk requirements\fP in \fBcbbackupmgr\-cloud\fP(7) for more information.
.RE
.SS "Optional"
.sp
\-\-obj\-access\-key\-id <access_key_id>
.RS 4
The access key id which has access to your chosen object store. This option
can be omitted when using the shared config functionality provided by your
chosen object store. Can alternatively be provided using the
\f(CRCB_OBJSTORE_ACCESS_KEY_ID\fP environment variable.
.sp
When using AWS, this option expects an access key id. See
\c
.URL "https://docs.aws.amazon.com/general/latest/gr/aws\-sec\-cred\-types.html#access\-keys\-and\-secret\-access\-keys" ""
for more information.
.sp
When using Azure, this option expects an account name. See
\c
.URL "https://docs.microsoft.com/en\-us/azure/storage/common/storage\-account\-overview#storage\-account\-endpoints" ""
for more information.
.sp
When using GCP, this option expects a client id. See
.URL "https://cloud.google.com/storage/docs/authentication" "" ""
for more information.
.RE
.sp
\-\-obj\-cacert <cert_path>
.RS 4
Specifies a CA certificate that will be used to verify the identity of the
object store being connected to.
.RE
.sp
\-\-obj\-endpoint <endpoint>
.RS 4
The host/address of your object store.
.RE
.sp
\-\-obj\-no\-ssl\-verify
.RS 4
Skips the SSL verification phase when connecting to the object store.
Specifying this flag will allow a connection using SSL encryption, but you
are vulnerable to a man\-in\-the\-middle attack.
.RE
.sp
\-\-obj\-region <region>
.RS 4
The region in which your bucket/container resides. For AWS this option may be
omitted when using the shared config functionality. See the AWS section of
the cloud documentation for more information.
.RE
.sp
\-\-obj\-secret\-access\-key <secret_access_key>
.RS 4
The secret access key which has access to you chosen object store. This
option can be omitted when using the shared config functionality provided by
your chosen object store. Can alternatively be provided using the
\f(CRCB_OBJSTORE_SECRET_ACCESS_KEY\fP environment variable.
.sp
When using AWS, this option expects a secret access key. See
\c
.URL "https://docs.aws.amazon.com/general/latest/gr/aws\-sec\-cred\-types.html#access\-keys\-and\-secret\-access\-keys" ""
for more information.
.sp
When using Azure, this option expects an account key. See
\c
.URL "https://docs.microsoft.com/en\-us/azure/storage/common/storage\-account\-keys\-manage?tabs=azure\-portal" ""
for more information.
.sp
When using GCP, this option expects a client secret. See
.URL "https://cloud.google.com/storage/docs/authentication" "" ""
for more information.
.RE
.sp
\-\-obj\-log\-level <level>
.RS 4
Set the log level for the cloud providers SDK. By default logging will be
disabled. Valid options are cloud provider specific and are listed below.
.sp
The valid options for the AWS SDK are \f(CRdebug\fP, \f(CRdebug\-with\-signing\fP,
\f(CRdebug\-with\-body\fP, \f(CRdebug\-with\-request\-retries\fP, \f(CRdebug\-with\-request\-errors\fP,
and \f(CRdebug\-with\-event\-stream\-body\fP.
.sp
The valid options for the Azure SDK are \f(CRinfo\fP, \f(CRdebug\fP, \f(CRdebug\-with\-request\-retries\fP and
\f(CRdebug\-with\-request\-retries\-and\-lro\fP.
.sp
The Google Storage SDK does not expose advanced logging configuration meaning
this option is explicitly ignored, however, this behavior may change in the
future.
.RE
.sp
\-\-obj\-auth\-by\-instance\-metadata
.RS 4
Depending on the cloud provider, using instance metadata for authentication
is disabled by default. Supplying this flag will allow the fetching
credentials/auth tokens from (VM) internal instance metadata endpoints.
.sp
By default, this option is disabled for AWS.
.sp
By default, this option is enabled for Azure.
.sp
By default, this option is enabled for GCP.
.RE
.sp
\-\-obj\-auth\-file
.RS 4
GCP offers the ability to use a file which contains credentials which will be
used to perform authentication. The \f(CR\-\-obj\-auth\-file\fP flag accepts a path to
an authentication file. This flag is unsupported for the AWS/Azure cloud
providers.
.RE
.sp
\-\-obj\-refresh\-token
.RS 4
GCP requires a refresh token when using static credentials, this will be used
to refresh oauth2 tokens when accessing remote storage.
.RE
.SS "AWS S3 Options"
.SS "Optional"
.sp
\-\-s3\-force\-path\-style
.RS 4
By default the updated virtual style paths will be used when interfacing with
AWS S3. This option will force the AWS SDK to use the alternative path style
URLs which are often required by S3 compatible object stores.
.RE
.SH "START AND END"
.sp
This sub\-command accepts a \f(CR\-\-start\fP and \f(CR\-\-end\fP flag. These flags accept
multiple values to allow you to flexibly operate on a range of backups.
.SS "Indexes"
.sp
Indexes may be supplied to operate on a range of backups, for example
\f(CR\-\-start 1 \-\-end 2\fP will include start at the first backup and will finish with
the second backup. Note that the first backup is 1 and not 0 and that the
\f(CR\-\-end\fP flag is inclusive.
.SS "Short Dates"
.sp
Short dates may be supplied in the format \f(CRday\-month\-year\fP. For example
\f(CR\-\-start 01\-08\-2020 \-\-end 31\-08\-2020\fP will operate on all the backups which
were taken during August of 2020. Note that the end date is inclusive.
.sp
When supplying short dates, you may supply \f(CRstart\fP or \f(CRoldest\fP as a placeholder
for the date on which the first backup in this repository was taken. The
keywords \f(CRend\fP or \f(CRlatest\fP may be used as a placeholder for the date last
backup in the repository was taken.
.SS "Backup Names"
.sp
Backup names may be supplied as they exist on disk. For example
\f(CR\-\-start 2020\-08\-13T20_01_08.894226137+01_00 \-\-end 2020\-08\-13T20_01_12.348300092+01_00\fP
will cause the sub\-command to operate on all the backups which inclusively fall
between these two backups.
.sp
When supplying backup names, you may supply \f(CRstart\fP or \f(CRoldest\fP as a
placeholder for the first backup in the repository. The keywords \f(CRend\fP or
\f(CRlatest\fP may be used  as a placeholder for the final backup in the repository.
.SH "EXAMPLES"
.sp
The remove command is used to remove a backup repository from disk. Below is an
example of how to run the remove command. The /data/backup directory is used as
the archive directory and the backup repository is named "example".
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr info \-\-archive /data/backups \-\-repo example \-\-all
Name     | Size    | # Backups  |
example  | 4.38MB  | 3          |

+  Backup                            | Size    | Type  | Source                 | Cluster UUID                      | Range  | Events  | Aliases  | Complete  |
+  2020\-06\-02T07_49_11.281004+01_00  | 1.69MB  | FULL  | http://localhost:8091  | c044f5eeb1dc16d0cd49dac29074b5f9  | N/A    | 0       | 1        | true      |

\-    Bucket   | Size    | Items  | Mutations  | Tombstones  | Views  | FTS  | Indexes  | CBAS  |
\-    example  | 1.69MB  | 4096   | 4096       | 0           | 0      | 0    | 0        | 0     |

+  Backup                            | Size    | Type  | Source                 | Cluster UUID                      | Range  | Events  | Aliases  | Complete  |
+  2020\-06\-03T07_49_52.577901+01_00  | 1.34MB  | INCR  | http://localhost:8091  | c044f5eeb1dc16d0cd49dac29074b5f9  | N/A    | 0       | 1        | true      |

\-    Bucket   | Size    | Items  | Mutations  | Tombstones  | Views  | FTS  | Indexes  | CBAS  |
\-    example  | 1.34MB  | 2048   | 2048       | 0           | 0      | 0    | 0        | 0     |

+  Backup                            | Size    | Type  | Source                 | Cluster UUID                      | Range  | Events  | Aliases  | Complete  |
+  2020\-06\-04T07_50_06.908787+01_00  | 1.34MB  | INCR  | http://localhost:8091  | c044f5eeb1dc16d0cd49dac29074b5f9  | N/A    | 0       | 1        | true      |

\-    Bucket   | Size    | Items  | Mutations  | Tombstones  | Views  | FTS  | Indexes  | CBAS  |
\-    example  | 1.34MB  | 2048   | 2048       | 0           | 0      | 0    | 0        | 0     |


$ cbbackupmgr remove \-a /data/backup \-r example
Backup repository `example` deleted successfully from archive `/tmp/backup`

$ cbbackupmgr info \-a ~/data/backups \-\-all
Name     | UUID                                  | Size  | # Repos  |
backups  | 0db3337c\-96b0\-4b3a\-a7fb\-bbfd53790e5f  | 0B    | 0        |
.fam
.fi
.if n .RE
.sp
The remove command can also be used to remove backups from inside a repository
given the following archive:
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr info \-a /data/backup \-r example
Name     | Size     | # Backups  |
example  | 36.01MB  | 3          |

  +  Backup                            | Size     | Type  | Source                 | Range  | Events  | Aliases  | Complete  |
  +  2019\-09\-18T11_13_58.136188+01_00  | 12.00MB  | FULL  | http://localhost:8091  | N/A    | 0       | 1        | true      |
  +  2019\-09\-19T11_14_29.026324+01_00  | 12.00MB  | INCR  | http://localhost:8091  | N/A    | 0       | 1        | true      |
  +  2019\-09\-19T11_14_40.410627+01_00  | 12.00MB  | INCR  | http://localhost:8091  | N/A    | 0       | 1        | true      |
  +  2019\-09\-20T11_14_43.410627+01_00  | 12.00MB  | INCR  | http://localhost:8091  | N/A    | 0       | 1        | true      |
.fam
.fi
.if n .RE
.sp
We can delete the first two backups using indices range such as 1,2:
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr remove \-a ~/backup_repo \-r example \-\-backups 1,2
Backup `2019\-09\-18T11_13_58.136188+01_00` deleted successfully from archive `/Users/carlosbetancourt/backup_repo` repository `example`
Backup `2019\-09\-19T11_14_29.026324+01_00` deleted successfully from archive `/Users/carlosbetancourt/backup_repo` repository `example`
All backups in range `1,2` were deleted
.fam
.fi
.if n .RE
.sp
To delete only backup \f(CR2019\-09\-19T11_14_29.026324+01_0\fP we can do as follows:
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr remove \-a ~/backup_repo \-r example \-\-backups 2019\-09\-19T11_14_29.026324+01_0
Backup `2019\-09\-19T11_14_29.026324+01_00` deleted successfully from archive `/Users/carlosbetancourt/backup_repo` repository `example`
.fam
.fi
.if n .RE
.sp
To delete backups between the 18\-09\-2019 and 19\-09\-2019 we can do as follows:
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr remove \-a ~/backup_repo \-r example \-\-backups 18\-09\-2019,19\-09\-2019
Backup `2019\-09\-18T11_13_58.136188+01_00` deleted successfully from archive `/Users/carlosbetancourt/backup_repo` repository `example`
Backup `2019\-09\-19T11_14_29.026324+01_00` deleted successfully from archive `/Users/carlosbetancourt/backup_repo` repository `example`
Backup `2019\-09\-19T11_14_40.410627+01_00` deleted successfully from archive `/Users/carlosbetancourt/backup_repo` repository `example`
Backup `2019\-09\-19T11_14_29.026324+01_00` deleted successfully from archive `/Users/carlosbetancourt/backup_repo` repository `example`
All backups in range `18\-09\-2019,18\-09\-2019` were deleted
.fam
.fi
.if n .RE
.sp
Finally, we can also provide exact backup archive name ranges such as
2019\-09\-18T11_13_58.136188+01_00,2019\-09\-19T11_14_29.026324+01_00.
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr remove \-a ~/backup_repo \-r example \-\-backups 2019\-09\-18T11_13_58.136188+01_00,2019\-09\-19T11_14_29.026324+01_00
Backup `2019\-09\-18T11_13_58.136188+01_00` deleted successfully from archive `/Users/carlosbetancourt/backup_repo` repository `example`
Backup `2019\-09\-19T11_14_29.026324+01_00` deleted successfully from archive `/Users/carlosbetancourt/backup_repo` repository `example`
All backups in range `2019\-09\-18T11_13_58.136188+01_00,2019\-09\-19T11_14_29.026324+01_00` were deleted
.fam
.fi
.if n .RE
.sp
Removing data that is stored in AWS S3 is very similar to removing a local repository/backup, below is an example
command which remove a given backup:
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr remove \-a s3://storage/backup_archive \-r backup_repo \-\-obj\-staging\-dir ~/backup\-archive \-\-backups \*(Aq2020\-04\-22T14_10_18.372643628+01_00\*(Aq
Backup `2020\-04\-22T14_10_18.372643628+01_00` deleted successfully from archive `backup_archive` repository `backup_repo`
.fam
.fi
.if n .RE
.SH "DISCUSSION"
.sp
The remove command is used to safely remove a backup repository from an archive.
This command is provided because only the cbbackupmgr utility should ever be
used to access or modify a backup archive. Removing a backup repository will
remove data permanently from disk. Data is not recoverable once it has been
removed.
.SH "ENVIRONMENT AND CONFIGURATION VARIABLES"
.sp
CB_ARCHIVE_PATH
.RS 4
Specifies the path to the backup archive. If the archive path is supplied as
a command line argument then this value is overridden.
.RE
.sp
CB_OBJSTORE_STAGING_DIRECTORY
.RS 4
Specifies the path to the staging directory. If the \f(CR\-\-obj\-staging\-dir\fP
argument is provided in the command line then this value is overridden.
.RE
.sp
CB_OBJSTORE_REGION
.RS 4
Specifies the object store region. If the \f(CR\-\-obj\-region\fP argument is provided
in the command line then this value is overridden.
.RE
.sp
CB_OBJSTORE_ACCESS_KEY_ID
.RS 4
Specifies the object store access key id. If the \f(CR\-\-obj\-access\-key\-id\fP
argument is provided in the command line this value is overridden.
.RE
.sp
CB_OBJSTORE_SECRET_ACCESS_KEY
.RS 4
Specifies the object store secret access key. If the
\f(CR\-\-obj\-secret\-access\-key\fP argument is provided in the command line this value
is overridden.
.RE
.sp
CB_OBJSTORE_REFRESH_TOKEN
.RS 4
Specifies the refresh token to use. If the \f(CR\-\-obj\-refresh\-token\fP argument is
provided in the command line, this value is overridden.
.RE
.sp
CB_AWS_ENABLE_EC2_METADATA
.RS 4
By default cbbackupmgr will disable fetching EC2 instance metadata. Setting
this environment variable to true will allow the AWS SDK to fetch metadata
from the EC2 instance endpoint.
.RE
.SH "SEE ALSO"
.sp
\fBcbbackupmgr\-config\fP(1),
\fBcbbackupmgr\-info\fP(1),
\fBcbbackupmgr\-strategies\fP(1)
.SH "CBBACKUPMGR"
.sp
Part of the \fBcbbackupmgr\fP(1) suite
.SH "AUTHOR"
.sp
Couchbase