'\" t
.\"     Title: cbbackupmgr-backup
.\"    Author: Couchbase
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2023-09-20
.\"    Manual: Couchbase Server Manual
.\"    Source: Couchbase Server 7.2.2-6401
.\"  Language: English
.\"
.TH "CBBACKUPMGR\-BACKUP" "1" "2023-09-20" "Couchbase Server 7.2.2\-6401" "Couchbase Server Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
cbbackupmgr-backup \- Backs up data from a Couchbase cluster
.SH "SYNOPSIS"
.sp
.nf
cbbackupmgr backup [\-\-archive <archive_dir>] [\-\-repo <repo_name>]
                   [\-\-cluster <url>] [\-\-username <username>]
                   [\-\-password <password>] [\-\-client\-cert <path>]
                   [\-\-client\-cert\-password <password>] [\-\-client\-key <path>]
                   [\-\-client\-key\-password <password>] [\-\-resume] [\-\-purge]
                   [\-\-threads <num>] [\-\-cacert <file>] [\-\-no\-ssl\-verify]
                   [\-\-value\-compression <type>] [\-\-no\-progress\-bar]
                   [\-\-skip\-last\-compaction] [\-\-consistency\-check <window>]
                   [\-\-full\-backup] [\-\-obj\-access\-key\-id <access_key_id>]
                   [\-\-obj\-cacert <cert_path>] [\-\-obj\-endpoint <endpoint>]
                   [\-\-obj\-no\-ssl\-verify] [\-\-obj\-region <region>]
                   [\-\-obj\-staging\-dir <staging_dir>]
                   [\-\-obj\-secret\-access\-key <secret_access_key>]
                   [\-\-s3\-force\-path\-style] [\-\-s3\-log\-level <level>]
                   [\-\-passphrase <passphrase>] [\-\-km\-key\-url <url>]
                   [\-\-km\-endpoint <endpoint>] [\-\-km\-region <region>]
                   [\-\-km\-access\-key\-id <id>] [\-\-km\-secret\-access\-key <key>]
                   [\-\-km\-auth\-file <path>]
.fi
.br
.SH "DESCRIPTION"
.sp
Backs up a Couchbase cluster into the backup repository specified. Before
running the backup command, a backup repository must be created. See
\fBcbbackupmgr\-config\fP(1) for more details on creating a backup
repository. The backup command uses information from the previous backup taken
in order to backup all new data on a Couchbase cluster. If no previous backup
exists then all data on the cluster is backed up. The backup is taken based on
the backup repository\(cqs backup configuration. Each backup will create a new
folder in the backup repository. This folder will contain all data from the
backup and is named to reflect the time that the backup was started.
.sp
As the backup runs, it tracks its progress which allows failed backups to be
resumed from the point where they left off. If a backup fails before it is
complete it is considered a partial backup. To attempt to complete the backup
process, the backup may be resumed with the \-\-resume flag. It may also be
deleted and resumed from the previous successful backup with the \-\-purge flag.
.sp
The backup command is capable of backing up data when there is a cluster
rebalance operation in progress. During a rebalance, the backup command will
track data as it moves around the cluster and complete the backup. However, users
should use caution when running backups during a rebalance since both the
rebalance and backup operations can be resource intensive and may cause
temporary performance degradations in other parts of the cluster. See the
\-\-threads flag for information on how to lower the impact of the backup command
on your Couchbase cluster.
.sp
The backup command is also capable of backing up data when there are server
failures in the target backup cluster. When a server failure occurs the backup
command will wait for 180 seconds for the failed server to come back online or
for the failed server to be failed over and removed from the cluster. If 180
seconds passes without the failed server coming back online or being failed over
then the backup command will mark the data on that node as failed and attempt to
back up the rest of the data from the cluster. The backup will be marked as a
partial backup in the backup archive and will need to be either resumed or
purged when the backup command is invoked again.
.SH "OPTIONS"
.sp
Below are a list of required and optional parameters for the backup command.
.SS "Required"
.sp
\-a,\-\-archive <archive_dir>
.RS 4
The location of the backup archive directory. When backing up directly to S3
prefix the archive path with \f(CRs3://${BUCKET_NAME}/\fP.
.RE
.sp
\-r,\-\-repo <repo_name>
.RS 4
The name of the backup repository to backup data into.
.RE
.sp
\-c,\-\-cluster <hostname>
.RS 4
The hostname of one of the nodes in the cluster to back up. See the
Host Formats section below for hostname specification details.
.RE
.sp
\-u,\-\-username <username>
.RS 4
The username for cluster authentication. The user must have the appropriate
privileges to take a backup.
.RE
.sp
\-p,\-\-password <password>
.RS 4
The password for cluster authentication. The user must have the appropriate
privileges to take a backup. If not password is supplied to this option then
you will be prompted to enter your password.
.RE
.sp
\-\-client\-cert <path>
.RS 4
The path to a client certificate used to authenticate when connecting to a
cluster. May be supplied with \f(CR\-\-client\-key\fP as an alternative to the
\f(CR\-\-username\fP and \f(CR\-\-password\fP flags.  See the CERTIFICATE AUTHENTICATION
section for more information.
.RE
.sp
\-\-client\-cert\-password <password>
.RS 4
The password for the certificate provided to the \f(CR\-\-client\-cert\fP flag, when
using this flag, the certificate/key pair is expected to be in the PKCS#12
format. See the CERTIFICATE AUTHENTICATION section for more information.
.RE
.sp
\-\-client\-key <path>
.RS 4
The path to the client private key whose public key is contained in the
certificate provided to the \f(CR\-\-client\-cert\fP flag. May be supplied with
\f(CR\-\-client\-cert\fP as an alternative to the \f(CR\-\-username\fP and \f(CR\-\-password\fP
flags. See the CERTIFICATE AUTHENTICATION section for more information.
.RE
.sp
\-\-client\-key\-password <password>
.RS 4
The password for the key provided to the \f(CR\-\-client\-key\fP flag, when using this
flag, the key is expected to be in the PKCS#8 format.  See the CERTIFICATE
AUTHENTICATION section for more information.
.RE
.SS "Optional"
.sp
\-\-resume
.RS 4
If the previous backup did not complete successfully it can be resumed from
where it left off by specifying this flag. Note that the resume and purge
flags may not be specified at the same time.
.RE
.sp
\-\-purge
.RS 4
If the previous backup did not complete successfully the partial backup will
be removed and restarted from the point of the previous successful backup by
specifying this flag. Note that the purge and resume flags may not be
specified at the same time.
.RE
.sp
\-\-no\-ssl\-verify
.RS 4
Skips the SSL verification phase. Specifying this flag will allow a
connection using SSL encryption, but will not verify the identity of the
server you connect to. You are vulnerable to a man\-in\-the\-middle attack if
you use this flag. Either this flag or the \-\-cacert flag must be specified
when using an SSL encrypted connection.
.RE
.sp
\-\-cacert <cert_path>
.RS 4
Specifies a CA certificate that will be used to verify the identity of the
server being connecting to. Either this flag or the \-\-no\-ssl\-verify flag
must be specified when using an SSL encrypted connection.
.RE
.sp
\-\-value\-compression <compression_policy>
.RS 4
Specifies a compression policy for backed up values. When Couchbase sends
data to the backup client the data stream may contain all compressed values,
all uncompressed values, or a mix of compressed and uncompressed values. To
backup all data in the same form that the backup client receives it you can
specify "unchanged". If you wish for all values to be uncompressed then you
can specify "uncompressed". This policy will however uncompress any
compressed values received from Couchbase and may increase the backup file
size. To compress all values you can specify "compressed". This will compress
any uncompressed values before writing them to disk. The default value for
this option is "compressed".
.RE
.sp
\-t,\-\-threads <num>
.RS 4
Specifies the number of concurrent clients to use when taking a backup.
Fewer clients means backups will take longer, but there will be less cluster
resources used to complete the backup. More clients means faster backups,
but at the cost of more cluster resource usage. This parameter defaults to 1
if it is not specified and it is recommended that this parameter is not set
to be higher than the number of CPUs on the machine where the backup is
taking place.
.RE
.sp
\-\-no\-progress\-bar
.RS 4
By default, a progress bar is printed to stdout so that the user can see how
long the backup is expected to take, the amount of data that is being
transferred per second, and the amount of data that has been backed up.
Specifying this flag disables the progress bar and is useful when running
automated jobs.
.RE
.sp
\-\-consistency\-check <window>
.RS 4
When a window larger than 1 is provided it will enable the consistency
checker. This will show a warning if the backup consistency window is larger
than the one provided in seconds. This is an Enterprise Edition feature and
is currently in developer preview. See DISCUSSION for more information.
.RE
.sp
\-\-full\-backup
.RS 4
Force a full backup in the same backup repository. This can be used to more
easily manage backups.
.RE
.SS "Cloud integration"
.sp
Native cloud integration is an Enterprise Edition feature which was introduced
in Couchbase Server 6.6.0.
.sp
Backing up directly to object store is only supported for Couchbase Server
6.6.0 and above. It\(cqs likely that backing up older clusters will result in
significantly higher memory consumption.
.sp
Multiple cloud providers are supported, see the list below for more information.
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Supported
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
AWS S3 (\f(CRs3://\fP)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
GCP Google Storage (\f(CRgs://\fP)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Azure Blob Storage in 7.1.2+ (\f(CRaz://\fP)
.RE
.RE
.SS "Required"
.sp
\-\-obj\-staging\-dir <staging_dir>
.RS 4
When performing an operation on an archive which is located in the cloud such
as AWS, the staging directory is used to store local meta data files. This
directory can be temporary (it\(cqs not treated as a persistent store) and is
only used during the backup. NOTE: Do not use \f(CR/tmp\fP as the \f(CRobj\-staging\-dir\fP.
See \f(CRDisk requirements\fP in \fBcbbackupmgr\-cloud\fP(7) for more information.
.RE
.SS "Optional"
.sp
\-\-obj\-access\-key\-id <access_key_id>
.RS 4
The access key id which has access to your chosen object store. This option
can be omitted when using the shared config functionality provided by your
chosen object store. Can alternatively be provided using the
\f(CRCB_OBJSTORE_ACCESS_KEY_ID\fP environment variable.
.sp
When using AWS, this option expects an access key id. See
\c
.URL "https://docs.aws.amazon.com/general/latest/gr/aws\-sec\-cred\-types.html#access\-keys\-and\-secret\-access\-keys" ""
for more information.
.sp
When using Azure, this option expects an account name. See
\c
.URL "https://docs.microsoft.com/en\-us/azure/storage/common/storage\-account\-overview#storage\-account\-endpoints" ""
for more information.
.sp
When using GCP, this option expects a client id. See
.URL "https://cloud.google.com/storage/docs/authentication" "" ""
for more information.
.RE
.sp
\-\-obj\-cacert <cert_path>
.RS 4
Specifies a CA certificate that will be used to verify the identity of the
object store being connected to.
.RE
.sp
\-\-obj\-endpoint <endpoint>
.RS 4
The host/address of your object store.
.RE
.sp
\-\-obj\-no\-ssl\-verify
.RS 4
Skips the SSL verification phase when connecting to the object store.
Specifying this flag will allow a connection using SSL encryption, but you
are vulnerable to a man\-in\-the\-middle attack.
.RE
.sp
\-\-obj\-region <region>
.RS 4
The region in which your bucket/container resides. For AWS this option may be
omitted when using the shared config functionality. See the AWS section of
the cloud documentation for more information.
.RE
.sp
\-\-obj\-secret\-access\-key <secret_access_key>
.RS 4
The secret access key which has access to you chosen object store. This
option can be omitted when using the shared config functionality provided by
your chosen object store. Can alternatively be provided using the
\f(CRCB_OBJSTORE_SECRET_ACCESS_KEY\fP environment variable.
.sp
When using AWS, this option expects a secret access key. See
\c
.URL "https://docs.aws.amazon.com/general/latest/gr/aws\-sec\-cred\-types.html#access\-keys\-and\-secret\-access\-keys" ""
for more information.
.sp
When using Azure, this option expects an account key. See
\c
.URL "https://docs.microsoft.com/en\-us/azure/storage/common/storage\-account\-keys\-manage?tabs=azure\-portal" ""
for more information.
.sp
When using GCP, this option expects a client secret. See
.URL "https://cloud.google.com/storage/docs/authentication" "" ""
for more information.
.RE
.sp
\-\-obj\-log\-level <level>
.RS 4
Set the log level for the cloud providers SDK. By default logging will be
disabled. Valid options are cloud provider specific and are listed below.
.sp
The valid options for the AWS SDK are \f(CRdebug\fP, \f(CRdebug\-with\-signing\fP,
\f(CRdebug\-with\-body\fP, \f(CRdebug\-with\-request\-retries\fP, \f(CRdebug\-with\-request\-errors\fP,
and \f(CRdebug\-with\-event\-stream\-body\fP.
.sp
The valid options for the Azure SDK are \f(CRinfo\fP, \f(CRdebug\fP, \f(CRdebug\-with\-request\-retries\fP and
\f(CRdebug\-with\-request\-retries\-and\-lro\fP.
.sp
The Google Storage SDK does not expose advanced logging configuration meaning
this option is explicitly ignored, however, this behavior may change in the
future.
.RE
.sp
\-\-obj\-auth\-by\-instance\-metadata
.RS 4
Depending on the cloud provider, using instance metadata for authentication
is disabled by default. Supplying this flag will allow the fetching
credentials/auth tokens from (VM) internal instance metadata endpoints.
.sp
By default, this option is disabled for AWS.
.sp
By default, this option is enabled for Azure.
.sp
By default, this option is enabled for GCP.
.RE
.sp
\-\-obj\-auth\-file
.RS 4
GCP offers the ability to use a file which contains credentials which will be
used to perform authentication. The \f(CR\-\-obj\-auth\-file\fP flag accepts a path to
an authentication file. This flag is unsupported for the AWS/Azure cloud
providers.
.RE
.sp
\-\-obj\-refresh\-token
.RS 4
GCP requires a refresh token when using static credentials, this will be used
to refresh oauth2 tokens when accessing remote storage.
.RE
.SS "AWS S3 Options"
.SS "Optional"
.sp
\-\-s3\-force\-path\-style
.RS 4
By default the updated virtual style paths will be used when interfacing with
AWS S3. This option will force the AWS SDK to use the alternative path style
URLs which are often required by S3 compatible object stores.
.RE
.SS "Encryption (Developer Preview)"
.sp
\-\-passphrase <passphrase>
.RS 4
Passphrase can be used instead of an external key manager. This is not
supported on production and should only be used in development or testing.
.RE
.sp
\-\-km\-key\-url <url>
.RS 4
Provides the Key Identifier in the external Key Management system. Currently
supported KMSs are AWS KMS, GCP KMS, Azure KeyVault, HashiCorp Vault Transit
secrets engine. The option can also be provided using the environmental
variable \f(CRCB_KM_KEY_URL\fP. For more on how to authenticate using the different
providers see \fBcbbackupmgr\-encryption\fP(7).
.sp
For AWS the expected key format is \f(CRawskms://<KEY\-ID|KEY\-ALIAS>\fP, for example
\f(CRawskms://alias\(rskeyAlias\fP.
.sp
For GCP the expected key format is \f(CRgcpkms://<KEY\-RESOURCE\-ID>\fP, for example
\f(CRgcpkms://projects/project\-id/locations/location/keyRings/keyring/cryptoKeys/key\fP.
.sp
For Azure key vault the expected key format is \f(CRazurekeyvault://<KEY\-IDENTIFIER>\fP
for example:
\f(CRazurekeyvault://vault\-name.vault.azure.net/object\-type/object\-name/object\-version\fP.
.sp
For HashiCorp Vault the expected format is \f(CRhashivaults://<HOST>/<KEY\-NAME>\fP
for example:
\f(CRhashivaults://127.0.0.1:8200/keyName\fP.
.RE
.sp
\-\-km\-region <region>
.RS 4
Required when using AWS KMS, it allows you to set the key region.
.RE
.sp
\-\-km\-endpoint <endpoint>
.RS 4
The host or address to use as your KMS. It will override the default SDK one.
.RE
.sp
\-\-km\-access\-key\-id <id>
.RS 4
The user ID used to connect to the key management service. It can also be
provided via \f(CRCB_KM_ACCESS_KEY_ID\fP environmental variable. Please refer
to \fBcbbackupmgr\-encryption\fP(7) for the required authentication for each
provider.
.RE
.sp
\-\-km\-secret\-access\-key <key>
.RS 4
The key used to connect to the key management service. It can also be
provided via the \f(CRCB_KM_SECRET_ACCESS_KEY\fP environmental variable. Please
refer to \fBcbbackupmgr\-encryption\fP(7) for the required authentication for
each provider.
.RE
.sp
\-\-km\-auth\-file <path>
.RS 4
The path to a file containing the authentication credentials for the key
management service. It can also be provided via the \f(CRCB_KM_AUTH_FILE\fP
environmental variable. Please refer to \fBcbbackupmgr\-encryption\fP(7) for the
required authentication for each provider.
.RE
.SH "HOST FORMATS"
.sp
When specifying a host/cluster for a command using the \f(CR\-c\fP/\f(CR\-\-cluster\fP flag, the following formats
are accepted:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttp://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://<srv>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://<srv>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR<addr>:<port>,<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR<scheme>://<addr>:<port>,<addr>:<port>\fP
.RE
.sp
The \f(CR<port>\fP portion of the host format may be omitted, in which case the default port will be used
for the scheme provided. For example, \f(CRhttp://\fP and \f(CRcouchbase://\fP will both default to 8091 where
\f(CRhttps://\fP and \f(CRcouchbases://\fP will default to 18091. When connecting to a host/cluster using a
non\-default port, the \f(CR<port>\fP portion of the host format must be specified.
.SS "Connection Strings (Multiple nodes)"
.sp
The \f(CR\-c\fP/\f(CR\-\-cluster\fP flag accepts multiple nodes in the format of a connection string; this is a
comma separated list of \f(CR<addr>:<port>\fP strings where \f(CR<scheme>\fP only needs to be specified once.
The main advantage of supplying multiple hosts is that in the event of a failure, the next host in
the list will be used.
.sp
For example, all of the following are valid connection strings:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRlocalhost,[::1]\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR10.0.0.1,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttp://10.0.0.1,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://10.0.0.1:12345,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://10.0.0.1,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://10.0.0.1:12345,10.0.0.2:12345\fP
.RE
.SS "SRV Records"
.sp
The \f(CR\-c\fP/\f(CR\-\-cluster\fP flag accepts DNS SRV records in place of a host/cluster address where the SRV
record will be resolved into a valid connection string. There are a couple of rules which must be
followed when supplying an SRV record which are as follows:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \f(CR<scheme>\fP portion must be either \f(CRcouchbase://\fP or \f(CRcouchbases://\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \f(CR<srv>\fP portion should be a hostname with no port
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \f(CR<srv>\fP portion must not be a valid IP address
.RE
.sp
For example, all of the following are valid connection string using an SRV record:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://hostname\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://hostname\fP
.RE
.SS "Alternate Addressing (CAO/K8S)"
.sp
Users of the CAO (Couchbase Autonomous Operator) or K8S may need to supply the
\f(CRnetwork=external\fP query parameter to force connection via the defined
alternate addressing.
.sp
For example, the following are valid connection strings:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://10.0.0.1:12345,10.0.0.2?network=default\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://10.0.0.1:12345,10.0.0.2?network=external\fP
.RE
.SH "CERTIFICATE AUTHENTICATION (MTLS AUTHENTICATION)"
.sp
This tool supports authenticating against a Couchbase Cluster by using certificate based authentication (mTLS
authentication). To use certificate based authentication a certificate/key must be supplied, there a currently
multiple ways this may be done.
.SS "PEM ENCODED CERTIFICATE/KEY"
.sp
An unencrypted PEM encoded certificate/key may be supplied by using:
\- \f(CR\-\-client\-cert <path>\fP
\- \f(CR\-\-client\-key <path>\fP
.sp
The file passed to \f(CR\-\-client\-cert\fP must contain the client certificate, and an optional chain required to authenticate
the client certificate.
.sp
The file passed to \f(CR\-\-client\-key\fP must contain at most one private key, the key can be in one of the following formats:
\- PKCS#1
\- PKCS#8
\- EC
.sp
Currently, only the following key types are supported:
\- RSA
\- ECDSA
\- ED25519
.SS "PEM ENCODED CERTIFICATE/PEM OR DER ENCRYPTED PKCS#8 KEY"
.sp
An encrypted PKCS#8 formatted key may be provided using:
\- \f(CR\-\-client\-cert <path>\fP
\- \f(CR\-\-client\-key <path>\fP
\- \f(CR\-\-client\-key\-password <password>\fP
.sp
The file passed to \f(CR\-\-client\-cert\fP must contain the client certificate, and an optional chain required to authenticate
the client certificate.
.sp
Currently, only the following key types are supported:
\- RSA
\- ECDSA
\- ED25519
.SS "ENCRYPTED PKCS#12 CERTIFICATE/KEY"
.sp
An encrypted PKCS#12 certificate/key may be provided using:
\- \f(CR\-\-client\-cert <path>\fP
\- \f(CR\-\-client\-cert\-password <password>\fP
.sp
The file passed to \f(CR\-\-client\-cert\fP must contain the client certificate and exactly one private key. It may also contain
the chain required to authenticate the client certificate.
.sp
Currently, only the following key types are supported:
\- RSA
\- ECDSA
\- ED25519
.SH "RBAC"
.sp
When performing a backup/restore with a user which is using RBAC, there are a
couple of things that should be taken into consideration each of which is
highlighted in this section.
.SS "Bucket Level"
.sp
Bucket level data may be backed up/restored using the \f(CRdata_backup\fP (Data
Backup & Restore) role.
.sp
The \f(CRdata_backup\fP role does not have access to cluster level data such as:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Analytics Synonyms
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Eventing Metadata
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
FTS Aliases
.RE
.sp
Backing up/restoring cluster level data with the \f(CRdata_backup\fP role will cause
permission errors like the one below.
.sp
.if n .RS 4
.nf
.fam C
Error backing up cluster: {"message":"Forbidden. User needs one of the following permissions","permissions":["cluster.fts!read"]}
.fam
.fi
.if n .RE
.sp
When presented with an error message such as the one above, there\(cqs two clear
options.
.sp
The first option is to provide the user with the required credentials using
either the cli, REST API or Couchbase Server WebUI. This can be done by editing
the user and adding the required role. See \f(CRCluster Level\fP for more information
about the required roles.
.sp
Secondly, backing up/restoring the specific service can be disabled. For
backups this must be done when configuring the repository with the \f(CRconfig\fP
command using the \f(CR\-\-disable\fP style flags. For restore, these flags may be used
directly to disable one or more services. See the backup/restore documentation
for more information.
.SS "Cluster Level"
.sp
Backing up/restoring cluster level data requires additional RBAC roles, each of
which is highlighted below:
.sp
Analytics Synonyms
.RS 4
\f(CRanalytics_admin\fP (Analytics Admin)
.RE
.sp
Eventing Metadata
.RS 4
\f(CReventing_admin\fP (Eventing Full Admin)
.RE
.sp
FTS Aliases
.RS 4
\f(CRfts_admin\fP (Search Admin)
.RE
.sp
These additional roles are required since this is cluster level data which may
encompass multiple buckets.
.SH "EXAMPLES"
.sp
The following command is used to take a backup of a Couchbase cluster.
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr config \-\-archive /data/backups \-\-repo example
$ cbbackupmgr backup \-a /data/backups \-r example \(rs
 \-c couchbase://172.23.10.5 \-u Administrator \-p password
.fam
.fi
.if n .RE
.sp
Once the backup has finished there will be a new directory in the specified
backup repository containing the backed up data. You can see this new directory
using the \fBcbbackupmgr\-info\fP(1) command.
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr info \-a /data/backups \-\-all

Name         | UUID                                 | Size     | # Repos  |
example | 32c97d5f\-821a\-4284\-840b\-9ee7cf8733a3 | 55.56MB  | 1        |

*  Name        | Size     | # Backups  |
*  Manchester  | 55.56MB  | 1          |

+    Backup                      | Size     | Type | Source               | Cluster UUID                     | Range | Events  | Aliases  | Complete  |
+    2019\-03\-15T13_52_27.18301Z  | 55.56MB  | FULL | http://172.23.10.5   | c044f5eeb1dc16d0cd49dac29074b5f9 | N/A   | 0       | 1        | true      |

\-      Bucket          | Size     | Items  | Mutations | Tombstones | Views  | FTS  | Indexes  | CBAS  |
\-      beer\-sample     | 6.85MB   | 7303   | 7303      | 0          | 1      | 0    | 1        | 0     |
\-      gamesim\-sample  | 2.86MB   | 586    | 586       | 0          | 1      | 0    | 1        | 0     |
\-      travel\-sample   | 42.72MB  | 31591  | 31591     | 0          | 0      | 0    | 10       | 0     |
.fam
.fi
.if n .RE
.sp
If a backup fails then it is considered a partial backup and the backup client
will not be able to back up any new data until the user decides whether to
resume or purge the partial backup. This decision is made by specifying either
the \-\-resume or the \-\-purge flag on the next invocation of the backup command.
Below is an example of how this process works if the user wants to resume a
backup.
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr config \-a /data/backups \-r example

$ cbbackupmgr backup \-a /data/backups \-r example \(rs
 \-c 172.23.10.5 \-u Administrator \-p password

Error backing up cluster: Not all data was backed up due to connectivity
issues. Check to make sure there were no server side failures during
backup. See backup logs for more details on what wasn\*(Aqt backed up.

$ cbbackupmgr backup \-a /data/backups \-r example \(rs
 \-c 172.23.10.5 \-u Administrator \-p password

Error backing up cluster: Partial backup error 2016\-02\-11T17:00:19.594970735\-08:00

$ cbbackupmgr backup \-a /data/backups \-r example \-c 172.23.10.5 \(rs
 \-u Administrator \-p password \-\-resume

Backup successfully completed
.fam
.fi
.if n .RE
.sp
To backup a cluster with a different amount of concurrent clients and decrease
the backup time you can specify the \-\-threads flag. Remember that specifying a
higher number of concurrent clients increases the amount of resources the
cluster uses to complete the backup. Below is an example of using 16 concurrent
clients.
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr config \-a /data/backups \-r example

$ cbbackupmgr backup \-a /data/backups \-r example \(rs
 \-c 172.23.10.5 \-u Administrator \-p password \-t 16
.fam
.fi
.if n .RE
.sp
To force the creation of a full backup, use the \f(CR\-\-full\-backup\fP flag. This will
result in cbbackupmgr streaming all the available data again. It\(cqs expected
that more disk space will be used and that the full backup will take longer
than performing an incremental backup (the default).
.sp
In the example below, the first backup is implicitly a full backup, the second
backup is an incremental (where no additional data needed to be backed up) and
the third is a forced full backup (note that we backed up the same amount of
items as the first backup).
.sp
.if n .RS 4
.nf
.fam C
$ cbbackupmgr backup \-a ~/Projects/couchbase\-archive \-r repo \-c 172.20.1.1 \-u Administrator \-p asdasd
Backing up to \*(Aq2021\-02\-09T13_35_15.426546996Z\*(Aq
Copied all data in 2.865028528s (Avg. 10.53MB/Sec)                                                                                        31591 items / 21.06MB
[=====================================================================================================================================================] 100.00%
Backup completed successfully
Backed up bucket "travel\-sample" succeeded
Mutations backed up: 31591, Mutations failed to backup: 0
Deletions backed up: 0, Deletions failed to backup: 0

$ cbbackupmgr backup \-a ~/Projects/couchbase\-archive \-r repo \-c 172.20.1.1 \-u Administrator \-p asdasd
Backing up to \*(Aq2021\-02\-09T13_35_21.580950579Z\*(Aq
Copied all data in 504.852625ms (Avg. 56.00KB/Sec)                                                                                            0 items / 56.00KB
[=====================================================================================================================================================] 100.00%
Backup completed successfully
Backed up bucket "travel\-sample" succeeded
Mutations backed up: 0, Mutations failed to backup: 0
Deletions backed up: 0, Deletions failed to backup: 0
Skipped due to purge number or conflict resolution: Mutations: 0 Deletions: 0

$ cbbackupmgr backup \-a ~/Projects/couchbase\-archive \-r repo \-c 172.20.1.1 \-u Administrator \-p asdasd \-\-fullbackup
Backing up to \*(Aq2021\-02\-09T13_35_24.18890408Z\*(Aq
Copied all data in 2.85286061s (Avg. 10.53MB/Sec)                                                                                         31591 items / 21.06MB
[=====================================================================================================================================================] 100.00%
Backup completed successfully
Backed up bucket "travel\-sample" succeeded
Mutations backed up: 31591, Mutations failed to backup: 0
Deletions backed up: 0, Deletions failed to backup: 0
Skipped due to purge number or conflict resolution: Mutations: 0 Deletions: 0
.fam
.fi
.if n .RE
.SH "COLLECTION AWARE BACKUPS"
.sp
The 7.0.0 release of Couchbase Server introduced collections supports. The
following section will briefly discuss how this affects backups created by
cbbackupmgr.
.SS "What makes a backup collection aware?"
.sp
cbbackupmgr is not limited to only backing up the cluster version it was
released with; it may be used to backup previous versions of Couchbase
Server. This means that cbbackupmgr is able to create backups which are
collection aware or unaware.
.sp
The distinction between collection aware/unaware is simple; if you backup
a cluster prior to 7.0.0 your backup will be collection unaware. If you
backup a cluster version which supports collections (starting at 7.0.0)
your backup will be collection aware.
.sp
The default behavior of backup for the cluster versions which support
collections is to back up all available scopes/collections in a bucket.
.SS "What if I don\(cqt want to use collections?"
.sp
This is perfectly valid use case and is supported by Couchbase Server and
cbbackupmgr. When interacting with backups created of a collection aware
cluster, cbbackupmgr will only output collection aware information if the
backup contains a non\-default collection manifest (which implies the use of
collections).
.sp
This means you may continue using cbbackupmgr without needing to interact with
collections. Note that you may still need to update/change the flags being
passed to some sub\-commands. For example, when examining a backup, you will
still need to use the \f(CR\-\-collection\-string\fP flag. For example instead of
\f(CR\-\-bucket default\fP you should supply \f(CR\-\-collection\-string default\fP.
.SH "DISCUSSION"
.sp
This command always backs up data incrementally. By using the vbucket sequence
number that is associated with each item, the backup command is able to examine
previous backups in order to determine where the last backup finished.
.sp
When backing up a cluster, data for each bucket is backed up in the following
order:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRBucket Settings\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRView Definitions\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRGlobal Secondary Index (GSI) Definitions\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRFull\-Text Index Definitions\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRKey\-Value Data\fP
.RE
.sp
The backup command will store everything that is persisted to disk on the
Couchbase Server nodes at the time the backup is started. Couchbase server is
consistent at a vBucket level and not across a whole bucket. The tool tries
to provide a strong consistency window by opening all connection to every
node at the same time. Being a distributed system there are times when this is
not possible such as when the cluster is under\-resourced or there are network
issues. These may affect the consistency of the backup across
the vBuckets. \f(CRcbbackupmgr backup\fP provides an Enterprise Edition, developer
preview feature that checks that the backup is inside a consistency window.
.SH "ROLLBACK"
.sp
During a backup, it\(cqs possible for cbbackupmgr to receive a rollback from the
cluster; this will be returned to you (the user) in the form of a message
similar to \f(CRclient received rollback, either purge this backup or create a new
backup repository\fP.
.sp
There are two sensible actions which can be taken at this point (which are
briefly alluded in the above message):
.sp
1) You can rerun the backup using the \f(CR\-\-purge\fP flag, this will remove the
failed backup creating a new incremental backup if possible, otherwise
falling back to creating a full backup.
2) You could create a new backup repository and begin creating backups there,
this method has the advantage of preserving any possible data which was
backed up prior to receiving the rollback.
.sp
In most cases, option one will be sufficient, however, if may be the case that
the partial backup taken by cbbackupmgr contains data which you don\(cqt want to
delete. In this case, option two allows you to retain this data which could be
restored using the \f(CR\-\-restore\-partial\-backups\fP flag.
.sp
Note that the \f(CR\-\-restore\-partial\-backups\fP flag is only supported for local
backups; backups stored in object store which failed due to a rollback must be
purged using the \f(CR\-\-purge\fP flag.
.SH "ENVIRONMENT AND CONFIGURATION VARIABLES"
.sp
CB_CLUSTER
.RS 4
Specifies the hostname of the Couchbase cluster to connect to. If the
hostname is supplied as a command line argument then this value is
overridden.
.RE
.sp
CB_USERNAME
.RS 4
Specifies the username for authentication to a Couchbase cluster. If the
username is supplied as a command line argument then this value is
overridden.
.RE
.sp
CB_PASSWORD
.RS 4
Specifies the password for authentication to a Couchbase cluster. If the
password is supplied as a command line argument then this value is
overridden.
.RE
.sp
CB_CLIENT_CERT
.RS 4
The path to a client certificate used to authenticate when connecting to a
cluster. May be supplied with \f(CRCB_CLIENT_KEY\fP as an alternative to the
\f(CRCB_USERNAME\fP and \f(CRCB_PASSWORD\fP variables. See the CERTIFICATE AUTHENTICATION
section for more information.
.RE
.sp
CB_CLIENT_CERT_PASSWORD
.RS 4
The password for the certificate provided to the \f(CRCB_CLIENT_CERT\fP variable,
when using this variable, the certificate/key pair is expected to be in the
PKCS#12 format. See the CERTIFICATE AUTHENTICATION section for more
information.
.RE
.sp
CB_CLIENT_KEY
.RS 4
The path to the client private key whose public key is contained in the
certificate provided to the \f(CRCB_CLIENT_CERT\fP variable. May be supplied with
\f(CRCB_CLIENT_CERT\fP as an alternative to the \f(CRCB_USERNAME\fP and \f(CRCB_PASSWORD\fP
variables. See the CERTIFICATE AUTHENTICATION section for more information.
.RE
.sp
CB_CLIENT_KEY_PASSWORD
.RS 4
The password for the key provided to the \f(CRCB_CLIENT_KEY\fP variable, when using
this variable, the key is expected to be in the PKCS#8 format.  See the
CERTIFICATE AUTHENTICATION section for more information.
.RE
.sp
CB_ARCHIVE_PATH
.RS 4
Specifies the path to the backup archive. If the archive path is supplied as
a command line argument then this value is overridden.
.RE
.sp
CB_OBJSTORE_STAGING_DIRECTORY
.RS 4
Specifies the path to the staging directory. If the \f(CR\-\-obj\-staging\-dir\fP
argument is provided in the command line then this value is overridden.
.RE
.sp
CB_OBJSTORE_REGION
.RS 4
Specifies the object store region. If the \f(CR\-\-obj\-region\fP argument is provided
in the command line then this value is overridden.
.RE
.sp
CB_OBJSTORE_ACCESS_KEY_ID
.RS 4
Specifies the object store access key id. If the \f(CR\-\-obj\-access\-key\-id\fP
argument is provided in the command line this value is overridden.
.RE
.sp
CB_OBJSTORE_SECRET_ACCESS_KEY
.RS 4
Specifies the object store secret access key. If the
\f(CR\-\-obj\-secret\-access\-key\fP argument is provided in the command line this value
is overridden.
.RE
.sp
CB_OBJSTORE_REFRESH_TOKEN
.RS 4
Specifies the refresh token to use. If the \f(CR\-\-obj\-refresh\-token\fP argument is
provided in the command line, this value is overridden.
.RE
.sp
CB_AWS_ENABLE_EC2_METADATA
.RS 4
By default cbbackupmgr will disable fetching EC2 instance metadata. Setting
this environment variable to true will allow the AWS SDK to fetch metadata
from the EC2 instance endpoint.
.RE
.sp
CB_ENCRYPTION_PASSPHRASE
.RS 4
Specifies the passphrase used for encryption.
.RE
.sp
CB_KM_KEY_URL
.RS 4
Specifies the URL identifying the encryption key on the KMS. See
\f(CR\-\-km\-key\-url\fP for the expected format and accepted KMSs.
.RE
.sp
CB_KM_ACCESS_ID
.RS 4
Specifies the key/user ID used to connect to the KMS.
.RE
.sp
CB_KM_SECRET_ACCESS_KEY
.RS 4
Specifies the secret key/token used to connect to the KMS.
.RE
.sp
CB_KM_AUTH_FILE
.RS 4
Specifies a path to a file containing the required credentials to connect to
the KMS.
.RE
.SH "FILES"
.sp
restrictions.json
.RS 4
Keeps a list of restrictions used to ensure data is not restored to the
place.
.RE
.sp
bucket\-config.json
.RS 4
Stores the bucket configuration settings for a bucket.
.RE
.sp
views.json
.RS 4
Stores the view definitions for a bucket.
.RE
.sp
gsi.json
.RS 4
Stores the global secondary index (GSI) definitions for a bucket.
.RE
.sp
full\-text.json
.RS 4
Stores the full\-text index definitions for a bucket.
.RE
.sp
shard\-*.fdb
.RS 4
Stores the key\-value data for a bucket bucket.
.RE
.SH "SEE ALSO"
.sp
\fBcbbackupmgr\-config\fP(1),
\fBcbbackupmgr\-info\fP(1),
\fBcbbackupmgr\-strategies\fP(1),
\fBcbbackupmgr\-cloud\fP(7),
man:cbbackupmgr\-encryption,
\fBcbbackupmgr\-network\-filesystems\fP(7)
.SH "CBBACKUPMGR"
.sp
Part of the \fBcbbackupmgr\fP(1) suite
.SH "AUTHOR"
.sp
Couchbase