'\" t
.\"     Title: cbdatarecovery
.\"    Author: Couchbase
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2023-09-20
.\"    Manual: Couchbase Server Manual
.\"    Source: Couchbase Server 7.2.2-6401
.\"  Language: English
.\"
.TH "CBDATARECOVERY" "1" "2023-09-20" "Couchbase Server 7.2.2\-6401" "Couchbase Server Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
cbdatarecovery \- Transfers key value data from a Couchbase Server data directory into an active cluster.
.SH "SYNOPSIS"
.sp
.nf
cbdatarecovery [\-\-cluster <connection_string>] [\-\-cacert <path>]
               [\-\-username <username>] [\-\-password <password>]
               [\-\-client\-cert <path>] [\-\-client\-cert\-password <password>]
               [\-\-client\-key <path>] [\-\-client\-key\-password <password>]
               [\-\-data\-path <path>] [\-\-map\-data <mappings>]
               [\-\-vbucket\-filter <filter>] [\-\-filter\-keys <regex>]
               [\-\-filter\-values <regex>] [\-\-replace\-ttl <type>]
               [\-\-replace\-ttl\-with <timestamp>]
               [\-\-include\-data <collection_strings>]
               [\-\-exclude\-data <collection_strings>]
               [\-\-vbucket\-state <state>] [\-\-log\-file <path>]
               [\-\-threads <threads>] [\-\-force\-updates]
               [\-\-create\-missing\-collections] [\-\-no\-ssl\-verify]
               [\-\-verbose] [\-\-no\-progress\-bar]
.fi
.br
.SH "DESCRIPTION"
.sp
cbdatarecovery transfers key value data stored in Couchstore files from a
Couchbase Server data directory into an active cluster. This can be used to
recover data from offline/failed over nodes.
.SH "OPTIONS"
.SS "Required"
.sp
\-c, \-\-cluster <connection_string>
.RS 4
A connection string representing a Couchbase node/cluster which will be the
destination for the recovered data. See the HOST FORMATS section for more
information.
.RE
.sp
\-u,\-\-username <username>
.RS 4
The username for cluster authentication. The user must have the appropriate
privileges to take a backup.
.RE
.sp
\-p,\-\-password <password>
.RS 4
The password for cluster authentication. The user must have the appropriate
privileges to take a backup. If not password is supplied to this option then
you will be prompted to enter your password.
.RE
.sp
\-\-client\-cert <path>
.RS 4
The path to a client certificate used to authenticate when connecting to a
cluster. May be supplied with \f(CR\-\-client\-key\fP as an alternative to the
\f(CR\-\-username\fP and \f(CR\-\-password\fP flags.  See the CERTIFICATE AUTHENTICATION
section for more information.
.RE
.sp
\-\-client\-cert\-password <password>
.RS 4
The password for the certificate provided to the \f(CR\-\-client\-cert\fP flag, when
using this flag, the certificate/key pair is expected to be in the PKCS#12
format. See the CERTIFICATE AUTHENTICATION section for more information.
.RE
.sp
\-\-client\-key <path>
.RS 4
The path to the client private key whose public key is contained in the
certificate provided to the \f(CR\-\-client\-cert\fP flag. May be supplied with
\f(CR\-\-client\-cert\fP as an alternative to the \f(CR\-\-username\fP and \f(CR\-\-password\fP
flags. See the CERTIFICATE AUTHENTICATION section for more information.
.RE
.sp
\-\-client\-key\-password <password>
.RS 4
The password for the key provided to the \f(CR\-\-client\-key\fP flag, when using this
flag, the key is expected to be in the PKCS#8 format.  See the CERTIFICATE
AUTHENTICATION section for more information.
.RE
.sp
\-d, \-\-data\-path <path>
.RS 4
The path to a Couchbase Server data directory. For example
\f(CR/opt/couchbase/lib/couchbase/data\fP.
.RE
.SS "Optional"
.sp
\-\-cacert <path>
.RS 4
Specifies a CA certificate that will be used to verify the identity of the
server being connecting to. Either this flag or the \-\-no\-ssl\-verify flag
must be specified when using an SSL encrypted connection.
.RE
.sp
\-\-map\-data <mappings>
.RS 4
Specified when you want to transfer source data into a different location.
For example this argument may be used to remap buckets/scopes/collections
with the restriction that they must be remapped at the same level. For
example a bucket may only be remapped to a bucket, a scope to a scope and a
collection to a collection. The argument expects a comma separated list of
collection string mappings e.g.
\f(CRbucket1=bucket2,bucket3.scope1=bucket3.scope2,bucket4.scope.collection1=bucket4.scope.collection2\fP
.RE
.sp
\-\-vbucket\-filter <filter>
.RS 4
Specifies a list of vBuckets that should be transferred. vBuckets are
specified as a comma separated list of integers/ranges. For example \f(CR0,1,2\fP
and \f(CR0\-2\fP represent the same subset of vBuckets. If no filter is provided,
then all vBuckets will be transferred.
.RE
.sp
\-\-filter\-keys <regex>
.RS 4
Only transfer data where the key matches a particular regular expression.
The regular expressions provided must follow
.URL "https://github.com/google/re2/wiki/Syntax" "RE2 syntax" "."
.RE
.sp
\-\-filter\-values <regex>
.RS 4
Only transfer data where the value matches a particular regular expression.
The regular expressions provided must follow
.URL "https://github.com/google/re2/wiki/Syntax" "RE2 syntax" "."
.RE
.sp
\-\-replace\-ttl <type>
.RS 4
Sets a new expiration (time\-to\-live) value for the specified keys. This
parameter can either be set to "none", "all" or "expired" and should be used
along with the \-\-replace\-ttl\-with flag. If "none" is supplied then the TTL
values are not changed. If "all" is specified then the TTL values for all
keys are replaced with the value of the \-\-replace\-ttl\-with flag.  If
"expired" is set then only keys which have already expired will have the
TTL\(cqs replaced.
.RE
.sp
\-\-replace\-ttl\-with <timestamp>
.RS 4
Updates the expiration for the keys specified by the \-\-replace\-ttl parameter.
The parameter has to be set when \-\-replace\-ttl is set to "all". There are two
options, RFC3339 time stamp format (2006\-01\-02T15:04:05\-07:00) or "0". When
"0" is specified the expiration will be removed. Please note that the RFC3339
value is converted to a Unix time stamp on the cbbackupmgr client. It is
important that the time on both the client and the Couchbase Server are the
same to ensure expiry happens correctly.
.RE
.sp
\-\-include\-data <collection_strings>
.RS 4
Only transfer data included in this comma list of collection strings. Note
that this flag can\(cqt be specified at the same time \f(CR\-\-exclude\-data\fP.
.RE
.sp
\-\-exclude\-data <collection_strings
.RS 4
Don\(cqt transfer the data for the buckets/scopes/collections in this comma
separated list of collection strings. Note that this flag can\(cqt be specified
at the same time as \f(CR\-\-include\-data\fP.
.RE
.sp
\-\-vbucket\-state <state>
.RS 4
Only transfer vBuckets which are in the provided stated. Accepts the values
\f(CRactive\fP, \f(CRreplica\fP or \f(CRdead\fP.
.RE
.sp
\-\-threads <threads>
.RS 4
Specifies the number of concurrent clients to use when transferring data.
Fewer clients means restores will take longer, but there will be less cluster
resources used to complete the restore. More clients means faster restores,
but at the cost of more cluster resource usage. This parameter defaults to 1
if it is not specified and it is recommended that this parameter is not set
to be higher than the number of CPUs on the machine where the restore is
taking place.
.RE
.sp
\-\-force\-updates
.RS 4
Forces data in the Couchbase cluster to be overwritten even if the data in
the cluster is newer. By default updates are not forced and all updates use
Couchbase\(cqs conflict resolution mechanism to ensure that if newer data exists
on the cluster that is not overwritten by older restore data.
.RE
.sp
\-\-create\-missing\-collections
.RS 4
Automatically create any scopes/collections which exist in the data directory
on disk but not in the remote cluster. This behavior is disabled by default.
.RE
.sp
\-\-no\-ssl\-verify
.RS 4
Skips the SSL verification phase. Specifying this flag will allow a
connection using SSL encryption, but will not verify the identity of the
server you connect to. You are vulnerable to a man\-in\-the\-middle attack if
you use this flag. Either this flag or the \-\-cacert flag must be specified
when using an SSL encrypted connection.
.RE
.sp
\-\-verbose
.RS 4
Increase logging verbosity; useful when debugging. Disabled by default.
.RE
.sp
\-\-no\-progress\-bar
.RS 4
By default, a progress bar is printed to stdout so that the user can see how
long the transfer is expected to take, the amount of data that is being
transferred per second, and the amount of data that has been transferred.
Specifying this flag disables the progress bar and is useful when running
automated jobs.
.RE
.SH "HOST FORMATS"
.sp
When specifying a host/cluster for a command using the \f(CR\-c\fP/\f(CR\-\-cluster\fP flag, the following formats
are accepted:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttp://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://<srv>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://<srv>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR<addr>:<port>,<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR<scheme>://<addr>:<port>,<addr>:<port>\fP
.RE
.sp
The \f(CR<port>\fP portion of the host format may be omitted, in which case the default port will be used
for the scheme provided. For example, \f(CRhttp://\fP and \f(CRcouchbase://\fP will both default to 8091 where
\f(CRhttps://\fP and \f(CRcouchbases://\fP will default to 18091. When connecting to a host/cluster using a
non\-default port, the \f(CR<port>\fP portion of the host format must be specified.
.SS "Connection Strings (Multiple nodes)"
.sp
The \f(CR\-c\fP/\f(CR\-\-cluster\fP flag accepts multiple nodes in the format of a connection string; this is a
comma separated list of \f(CR<addr>:<port>\fP strings where \f(CR<scheme>\fP only needs to be specified once.
The main advantage of supplying multiple hosts is that in the event of a failure, the next host in
the list will be used.
.sp
For example, all of the following are valid connection strings:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRlocalhost,[::1]\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR10.0.0.1,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttp://10.0.0.1,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://10.0.0.1:12345,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://10.0.0.1,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://10.0.0.1:12345,10.0.0.2:12345\fP
.RE
.SS "SRV Records"
.sp
The \f(CR\-c\fP/\f(CR\-\-cluster\fP flag accepts DNS SRV records in place of a host/cluster address where the SRV
record will be resolved into a valid connection string. There are a couple of rules which must be
followed when supplying an SRV record which are as follows:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \f(CR<scheme>\fP portion must be either \f(CRcouchbase://\fP or \f(CRcouchbases://\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \f(CR<srv>\fP portion should be a hostname with no port
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \f(CR<srv>\fP portion must not be a valid IP address
.RE
.sp
For example, all of the following are valid connection string using an SRV record:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://hostname\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://hostname\fP
.RE
.SS "Alternate Addressing (CAO/K8S)"
.sp
Users of the CAO (Couchbase Autonomous Operator) or K8S may need to supply the
\f(CRnetwork=external\fP query parameter to force connection via the defined
alternate addressing.
.sp
For example, the following are valid connection strings:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://10.0.0.1:12345,10.0.0.2?network=default\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://10.0.0.1:12345,10.0.0.2?network=external\fP
.RE
.SH "CERTIFICATE AUTHENTICATION (MTLS AUTHENTICATION)"
.sp
This tool supports authenticating against a Couchbase Cluster by using certificate based authentication (mTLS
authentication). To use certificate based authentication a certificate/key must be supplied, there a currently
multiple ways this may be done.
.SS "PEM ENCODED CERTIFICATE/KEY"
.sp
An unencrypted PEM encoded certificate/key may be supplied by using:
\- \f(CR\-\-client\-cert <path>\fP
\- \f(CR\-\-client\-key <path>\fP
.sp
The file passed to \f(CR\-\-client\-cert\fP must contain the client certificate, and an optional chain required to authenticate
the client certificate.
.sp
The file passed to \f(CR\-\-client\-key\fP must contain at most one private key, the key can be in one of the following formats:
\- PKCS#1
\- PKCS#8
\- EC
.sp
Currently, only the following key types are supported:
\- RSA
\- ECDSA
\- ED25519
.SS "PEM ENCODED CERTIFICATE/PEM OR DER ENCRYPTED PKCS#8 KEY"
.sp
An encrypted PKCS#8 formatted key may be provided using:
\- \f(CR\-\-client\-cert <path>\fP
\- \f(CR\-\-client\-key <path>\fP
\- \f(CR\-\-client\-key\-password <password>\fP
.sp
The file passed to \f(CR\-\-client\-cert\fP must contain the client certificate, and an optional chain required to authenticate
the client certificate.
.sp
Currently, only the following key types are supported:
\- RSA
\- ECDSA
\- ED25519
.SS "ENCRYPTED PKCS#12 CERTIFICATE/KEY"
.sp
An encrypted PKCS#12 certificate/key may be provided using:
\- \f(CR\-\-client\-cert <path>\fP
\- \f(CR\-\-client\-cert\-password <password>\fP
.sp
The file passed to \f(CR\-\-client\-cert\fP must contain the client certificate and exactly one private key. It may also contain
the chain required to authenticate the client certificate.
.sp
Currently, only the following key types are supported:
\- RSA
\- ECDSA
\- ED25519
.SH "AUTOMATIC COLLECTION CREATION"
.sp
By design, users may not recreate the \f(CR_default\fP collection once it has been
deleted. Therefore, this means that the \f(CR_default\fP collection can\(cqt (and won\(cqt)
be recreated if it\(cqs missing. Before performing a transfer, a check will take
place to see if the \f(CR_default\fP collection will be required when it\(cqs missing.
If this is the case, the command will exit early and you will be required to
remap the \f(CR_default\fP collection using the \f(CR\-\-map\-data\fP flag.
.SH "REMAPPING"
.sp
During a transfer, scopes/collections can be remapped from one location to
another. There are several rules that are enforced when remapping
scopes/collections, they are as follows:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
You must be running an Enterprise Edition version of Couchbase Server.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
You may not remap the \f(CR_default\fP scope (discussed in THE DEFAULT SCOPE).
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
You may only remap scopes/collections at the same level meaning scopes may
be remapped to other scopes, and collections to other collections, however, a
scope can\(cqt be remapped to a collection or vice versa.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Scopes/collections may only be remapped within the same bucket. For example
the mapping \f(CRbucket1.scope.collection=bucket2.scope.collection\fP is invalid.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Scopes/collections may only be remapped once. For example the mapping
\f(CRbucket1.scope1=bucket1.scope2,bucket1.scope1=bucket1.scope3\fP is invalid.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Remapping may only take place at one level at once meaning that if a parent
bucket/scope is already remapped, the child scopes/collections may not also
be remapped. For example the mapping
\f(CRbucket1.scope1=bucket1.scope2,bucket1.scope1.collection1=bucket1.scope3.collection9\fP
is invalid.
.RE
.SS "REMAPPING A SCOPE/COLLECTION WITHOUT RENAMING"
.sp
During a transfer, it\(cqs possible for a scope/collection to encounter a conflict
(for example, because it has been recreated). It may not be preferable to
rename the scope/collection during the transfer.
.sp
For this reason, the \f(CR\-\-map\-data\fP flag, allows you to remap a scope/collection
to itself; this indicates that the scope/collection that exists in the target
(with a different id) should be treated as the same.
.sp
As an example, the following error message indicates that a collection has been
recreated prior to a restore.
.sp
.if n .RS 4
.nf
.fam C
Error restoring cluster: collection 8 with name \*(Aqcollection1\*(Aq in the scope \*(Aq_default\*(Aq exists with a different name/id on the cluster, a manual remap is required
.fam
.fi
.if n .RE
.sp
Using the \f(CR\-\-map\-data\fP flag with the argument
\f(CRbucket._default.collection1=bucket._default.collection1\fP would cause
\f(CRcbbackupmgr\fP to treat \f(CRcollection1\fP (with id 8) as \f(CRcollection1\fP (with the id
it exists with in the target).
.SS "THE DEFAULT SCOPE"
.sp
As mentioned in AUTOMATIC COLLECTION CREATION, it\(cqs not possible to recreate
the \f(CR_default\fP scope/collection. This means you can\(cqt remap the \f(CR_default\fP
scope because the tool may be unable to create a destination scope/collection.
This may be worked around by remapping each collection inside the \f(CR_default\fP
scope.
.SS "BUCKET TO COLLECTION REMAPPING"
.sp
As discussed in REMAPPING, it\(cqs not possible to remap data at different levels;
buckets must be remapped to buckets, scopes to scopes and collections to
collections. However, there is one supported edge case, which is remapping a
bucket into a collection to allow migration from a collection unaware to
collection aware datasets.
.sp
To remap a bucket into a collection using \f(CR\-\-map\-data\fP you may supply
\f(CR\-\-map\-data bucket._default._default=bucket.scope.collection\fP. This
functionality is compatible with cross bucket mapping, for example you may also
supply \f(CR\-\-map\-data bucket1._default._default=bucket2.scope.collection\fP.
.sp
Note that once you\(cqve provided a mapping to remap a bucket into a collection
you may not remap that bucket elsewhere. For example \f(CR\-\-map\-data
bucket1._default._default=bucket2.scope.collection,bucket1=bucket3\fP is invalid.
.SS "REMAPPING MULTIPLE DATA SOURCES INTO A SINGLE TARGET SOURCE"
.sp
As outlined in the rules discussed in REMAPPING, it\(cqs not possible to remap a
bucket/scope/collection multiple times, however, it is possible to remap to a
single destination multiple times. For example the mapping
\f(CRbucket1=dest,bucket2=dest,bucket3=dest\fP is valid.
.sp
Although valid, this manor of remapping is dangerous and can result in data not
being transferred due to conflicting key spaces. If this style of remapping is
detected a warning will be printed before proceeding.
.SH "OPERATIONS DURING MAJOR CLUSTER CONFIGURATION CHANGES"
.sp
Operations (commands or sub\-commands) which connect to a cluster are not
supported during major cluster configuration changes.
.sp
For example, performing an import/export, making a backup or performing a
restore whilst changing the TLS configuration/security settings is unsupported.
.sp
These types of changes (e.g. changing the TLS mode to strict) are not expected
to be time consuming so it\(cqs generally expected that operations should be
started after completing the configuration change.
.sp
Please note that this does not include rebalances; operations may be performed
during a rebalance. The reason for this distinction, is that major cluster
configuration changes are generally quick, whilst rebalances for large data
sets may be time consuming.
.SH "EXAMPLES"
.sp
The cbdatarecovery tool may be used to recover key value data from a
Couchbase Server data directory. By default, all the active vBuckets for all
the detected buckets will be transferred.
.sp
.if n .RS 4
.nf
.fam C
$ cbdatarecovery \-c 172.20.1.1 \-u Administrator \-p asdasd \-d /opt/couchbase/lib/couchbase/data
Recovering to \*(Aq172.20.1.1\*(Aq
Copied all data in 505ms (Avg. 11.06MB/Sec)                                                                               17722 items / 11.06MB
[=====================================================================================================================================] 100.00%

| Transfer
| \-\-\-\-\-\-\-\-
| Status    | Avg Transfer Rate | Started At                        | Finished At                     | Duration |
| Succeeded | 11.06MB           | Tue, 23 Feb 2021 11:13:51 +0000/s | Tue, 23 Feb 2021 11:13:52 +0000 | 535ms    |

| Bucket
| \-\-\-\-\-\-
| Name        | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| beer\-sample | Succeeded | 740.46KB    | 740.46KB/s        | Tue, 23 Feb 2021 11:13:51 +0000 | Tue, 23 Feb 2021 11:13:51 +0000 | 21ms     |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 1836     | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |

| Bucket
| \-\-\-\-\-\-
| Name           | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| gamesim\-sample | Succeeded | 29.82KB     | 29.82KB/s         | Tue, 23 Feb 2021 11:13:51 +0000 | Tue, 23 Feb 2021 11:13:51 +0000 | 3ms      |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 137      | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |

| Bucket
| \-\-\-\-\-\-
| Name          | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| travel\-sample | Succeeded | 10.31MB     | 10.31MB/s         | Tue, 23 Feb 2021 11:13:51 +0000 | Tue, 23 Feb 2021 11:13:52 +0000 | 222ms    |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 15749    | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |
.fam
.fi
.if n .RE
.sp
To recover only a subset of the available buckets, the \f(CR\-\-include\-data\fP and
\f(CR\-\-exclude\-flags\fP may be used. Note that these flags are mutually exclusive
meaning they can\(cqt be used at the same time.
.sp
.if n .RS 4
.nf
.fam C
$ cbdatarecovery \-c 172.20.1.1 \-u Administrator \-p asdasd \-d /opt/couchbase/lib/couchbase/data \-\-include\-data travel\-sample
Recovering to \*(Aq172.20.1.1\*(Aq
Copied all data in 273ms (Avg. 10.31MB/Sec)                                                                              15749 items / 10.31MB
[====================================================================================================================================] 100.00%

| Transfer
| \-\-\-\-\-\-\-\-
| Status    | Avg Transfer Rate | Started At                        | Finished At                     | Duration |
| Succeeded | 10.31MB           | Tue, 23 Feb 2021 11:14:14 +0000/s | Tue, 23 Feb 2021 11:14:15 +0000 | 300ms    |

| Bucket
| \-\-\-\-\-\-
| Name          | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| travel\-sample | Succeeded | 10.31MB     | 10.31MB/s         | Tue, 23 Feb 2021 11:14:14 +0000 | Tue, 23 Feb 2021 11:14:15 +0000 | 189ms    |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 15749    | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |

$ cbdatarecovery \-c 172.20.1.1 \-u Administrator \-p asdasd \-d /opt/couchbase/lib/couchbase/data \-\-exclude\-data travel\-sample
Recovering to \*(Aq172.20.1.1\*(Aq
Copied all data in 202ms (Avg. 770.28KB/Sec)                                                                              1973 items / 770.28KB
[=====================================================================================================================================] 100.00%

| Transfer
| \-\-\-\-\-\-\-\-
| Status    | Avg Transfer Rate | Started At                        | Finished At                     | Duration |
| Succeeded | 770.28KB          | Tue, 23 Feb 2021 11:26:43 +0000/s | Tue, 23 Feb 2021 11:26:43 +0000 | 227ms

| Bucket
| \-\-\-\-\-\-
| Name        | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| beer\-sample | Succeeded | 740.46KB    | 740.46KB/s        | Tue, 23 Feb 2021 11:26:43 +0000 | Tue, 23 Feb 2021 11:26:43 +0000 | 26ms     |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 1836     | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |

| Bucket
| \-\-\-\-\-\-
| Name           | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| gamesim\-sample | Succeeded | 29.82KB     | 29.82KB/s         | Tue, 23 Feb 2021 11:26:43 +0000 | Tue, 23 Feb 2021 11:26:43 +0000 | 4ms      |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 137      | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |
.fam
.fi
.if n .RE
.sp
To recover only a subset of the available vBuckets, the \f(CR\-\-vbucket\-filter\fP flag
may be used. Note that by default all the available vBuckets will be recovered.
.sp
.if n .RS 4
.nf
.fam C
$ cbdatarecovery \-c 172.20.1.1 \-u Administrator \-p asdasd \-d /opt/couchbase/lib/couchbase/data \-\-vbucket\-filter 0\-128
Recovering to \*(Aq172.20.1.1\*(Aq
Copied all data in 199ms (Avg. 5.31MB/Sec)                                                                                 7971 items / 5.31MB
[====================================================================================================================================] 100.00%

| Transfer
| \-\-\-\-\-\-\-\-
| Status    | Avg Transfer Rate | Started At                        | Finished At                     | Duration |
| Succeeded | 5.31MB            | Tue, 23 Feb 2021 11:28:05 +0000/s | Tue, 23 Feb 2021 11:28:05 +0000 | 227ms

| Bucket
| \-\-\-\-\-\-
| Name          | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| travel\-sample | Succeeded | 5.31MB      | 5.31MB/s          | Tue, 23 Feb 2021 11:28:05 +0000 | Tue, 23 Feb 2021 11:28:05 +0000 | 114ms    |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 7971     | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |
.fam
.fi
.if n .RE
.sp
When recovering data to a different cluster or a cluster which has changed over
time, it\(cqs possible for some scopes/collections to have been dropped. This may
cause the recovery to fail because the required scopes/collections no longer
exist. The \f(CR\-\-auto\-create\-collections\fP flag can be used to automatically create
any missing scopes/collections.
.sp
.if n .RS 4
.nf
.fam C
$ cbdatarecovery \-c 172.20.1.1 \-u Administrator \-p asdasd \-d /opt/couchbase/lib/couchbase/data \-\-auto\-create\-collections
Recovering to \*(Aq172.20.1.1\*(Aq
Copied all data in 534ms (Avg. 11.06MB/Sec)                                                                               17722 items / 11.06MB
[=====================================================================================================================================] 100.00%

| Transfer
| \-\-\-\-\-\-\-\-
| Status    | Avg Transfer Rate | Started At                        | Finished At                     | Duration |
| Succeeded | 11.06MB           | Tue, 23 Feb 2021 11:15:19 +0000/s | Tue, 23 Feb 2021 11:15:20 +0000 | 563ms    |

| Bucket
| \-\-\-\-\-\-
| Name        | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| beer\-sample | Succeeded | 740.46KB    | 740.46KB/s        | Tue, 23 Feb 2021 11:15:20 +0000 | Tue, 23 Feb 2021 11:15:20 +0000 | 25ms     |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 1836     | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |

| Bucket
| \-\-\-\-\-\-
| Name           | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| gamesim\-sample | Succeeded | 29.82KB     | 29.82KB/s         | Tue, 23 Feb 2021 11:15:20 +0000 | Tue, 23 Feb 2021 11:15:20 +0000 | 3ms      |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 137      | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |

| Bucket
| \-\-\-\-\-\-
| Name          | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| travel\-sample | Succeeded | 10.31MB     | 10.31MB/s         | Tue, 23 Feb 2021 11:15:20 +0000 | Tue, 23 Feb 2021 11:15:20 +0000 | 200ms    |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 15749    | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |
.fam
.fi
.if n .RE
.sp
To recover only \f(CRreplica\fP vBuckets, the \f(CR\-\-vbucket\-state\fP flag may be used.
This flag accepts either \f(CRactive\fP or \f(CRreplica\fP resulting in the recovery of
only the vBuckets in the provided state. Note that by default only \f(CRactive\fP
vBuckets will be recovered.
.sp
In the examples below, note the difference in the number of items recovered
when recovering replica vBuckets; this is due to the way active/replica
vBuckets are distributed.
.sp
.if n .RS 4
.nf
.fam C
$ cbdatarecovery \-c 172.20.1.1 \-u Administrator \-p asdasd \-d /opt/couchbase/lib/couchbase/data
Recovering to \*(Aq172.20.1.1\*(Aq
Copied all data in 279ms (Avg. 10.31MB/Sec)                                                                              15749 items / 10.31MB
[====================================================================================================================================] 100.00%

| Transfer
| \-\-\-\-\-\-\-\-
| Status    | Avg Transfer Rate | Started At                        | Finished At                     | Duration |
| Succeeded | 10.31MB           | Tue, 23 Feb 2021 11:17:52 +0000/s | Tue, 23 Feb 2021 11:17:53 +0000 | 306ms

| Bucket
| \-\-\-\-\-\-
| Name          | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| travel\-sample | Succeeded | 10.31MB     | 10.31MB/s         | Tue, 23 Feb 2021 11:17:52 +0000 | Tue, 23 Feb 2021 11:17:53 +0000 | 194ms    |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 15749    | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |

$ cbdatarecovery \-c 172.20.1.1 \-u Administrator \-p asdasd \-d /opt/couchbase/lib/couchbase/data \-\-vbucket\-state replica
Recovering to \*(Aq172.20.1.1\*(Aq
Copied all data in 188ms (Avg. 10.33MB/Sec)                                                                              15893 items / 10.33MB
[====================================================================================================================================] 100.00%

| Transfer
| \-\-\-\-\-\-\-\-
| Status    | Avg Transfer Rate | Started At                        | Finished At                     | Duration |
| Succeeded | 10.33MB           | Tue, 23 Feb 2021 11:17:55 +0000/s | Tue, 23 Feb 2021 11:17:55 +0000 | 213ms

| Bucket
| \-\-\-\-\-\-
| Name          | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| travel\-sample | Succeeded | 10.33MB     | 10.33MB/s         | Tue, 23 Feb 2021 11:17:55 +0000 | Tue, 23 Feb 2021 11:17:55 +0000 | 101ms    |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 15893    | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |
.fam
.fi
.if n .RE
.sp
When recovering data to a cluster which has changed over time, it\(cqs possible
for one or more target scopes/collections to have been recreated. The
\f(CR\-\-map\-data\fP flag can be used to recover data to a scope/collection whose id
has changed (but the name remains the same).
.sp
.if n .RS 4
.nf
.fam C
$ cbdatarecovery \-c 172.20.1.1 \-u Administrator \-p asdasd \-d /opt/couchbase/lib/couchbase/data \(rs
    \-\-map\-data travel\-sample.inventory=travel\-sample.inventory
Recovering to \*(Aq172.20.1.1\*(Aq
Copied all data in 290ms (Avg. 10.31MB/Sec)                                                                              15749 items / 10.31MB
[====================================================================================================================================] 100.00%

| Transfer
| \-\-\-\-\-\-\-\-
| Status    | Avg Transfer Rate | Started At                        | Finished At                     | Duration |
| Succeeded | 10.31MB           | Tue, 23 Feb 2021 11:46:38 +0000/s | Tue, 23 Feb 2021 11:46:38 +0000 | 318ms

| Bucket
| \-\-\-\-\-\-
| Name          | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| travel\-sample | Succeeded | 10.31MB     | 10.31MB/s         | Tue, 23 Feb 2021 11:46:38 +0000 | Tue, 23 Feb 2021 11:46:38 +0000 | 201ms    |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 15749    | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |
.fam
.fi
.if n .RE
.sp
The \f(CR\-\-map\-data\fP flag may also be used to remap data from one location to
another, for example to rename a scope/collection. Note the addition of the
\f(CR\-\-auto\-create\-collections\fP flag because in this case the scope \f(CRstorage\fP did
not exist.
.sp
.if n .RS 4
.nf
.fam C
$ cbdatarecovery \-c 172.20.1.1 \-u Administrator \-p asdasd \-d /opt/couchbase/lib/couchbase/data \(rs
    \-\-map\-data travel\-sample.inventory=travel\-sample.storage \-\-auto\-create\-collections
Recovering to \*(Aq172.20.1.1\*(Aq
Copied all data in 401ms (Avg. 10.31MB/Sec)                                                                              15749 items / 10.31MB
[====================================================================================================================================] 100.00%

| Transfer
| \-\-\-\-\-\-\-\-
| Status    | Avg Transfer Rate | Started At                        | Finished At                     | Duration |
| Succeeded | 10.31MB           | Tue, 23 Feb 2021 11:20:23 +0000/s | Tue, 23 Feb 2021 11:20:23 +0000 | 429ms

| Bucket
| \-\-\-\-\-\-
| Name          | Status    | Transferred | Avg Transfer Rate | Started At                      | Finished At                     | Duration |
| travel\-sample | Succeeded | 10.31MB     | 10.31MB/s         | Tue, 23 Feb 2021 11:20:23 +0000 | Tue, 23 Feb 2021 11:20:23 +0000 | 227ms    |
|
| Mutations                    | Deletions                    | Expirations                  |
| \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-                    | \-\-\-\-\-\-\-\-\-\-\-                  |
| Received | Errored | Skipped | Received | Errored | Skipped | Received | Errored | Skipped |
| 15749    | 0       | 0       | 0        | 0       | 0       | 0        | 0       | 0       |
.fam
.fi
.if n .RE
.SH "ENVIRONMENT AND CONFIGURATION VARIABLES"
.sp
CB_CLUSTER
.RS 4
Specifies the hostname of the Couchbase cluster to connect to. If the
hostname is supplied as a command line argument then this value is
overridden.
.RE
.sp
CB_USERNAME
.RS 4
Specifies the username for authentication to a Couchbase cluster. If the
username is supplied as a command line argument then this value is
overridden.
.RE
.sp
CB_PASSWORD
.RS 4
Specifies the password for authentication to a Couchbase cluster. If the
password is supplied as a command line argument then this value is
overridden.
.RE
.sp
CB_CLIENT_CERT
.RS 4
The path to a client certificate used to authenticate when connecting to a
cluster. May be supplied with \f(CRCB_CLIENT_KEY\fP as an alternative to the
\f(CRCB_USERNAME\fP and \f(CRCB_PASSWORD\fP variables. See the CERTIFICATE AUTHENTICATION
section for more information.
.RE
.sp
CB_CLIENT_CERT_PASSWORD
.RS 4
The password for the certificate provided to the \f(CRCB_CLIENT_CERT\fP variable,
when using this variable, the certificate/key pair is expected to be in the
PKCS#12 format. See the CERTIFICATE AUTHENTICATION section for more
information.
.RE
.sp
CB_CLIENT_KEY
.RS 4
The path to the client private key whose public key is contained in the
certificate provided to the \f(CRCB_CLIENT_CERT\fP variable. May be supplied with
\f(CRCB_CLIENT_CERT\fP as an alternative to the \f(CRCB_USERNAME\fP and \f(CRCB_PASSWORD\fP
variables. See the CERTIFICATE AUTHENTICATION section for more information.
.RE
.sp
CB_CLIENT_KEY_PASSWORD
.RS 4
The password for the key provided to the \f(CRCB_CLIENT_KEY\fP variable, when using
this variable, the key is expected to be in the PKCS#8 format.  See the
CERTIFICATE AUTHENTICATION section for more information.
.RE
.SH "AUTHOR"
.sp
Couchbase