'\" t
.\"     Title: cbdocloader
.\"    Author: Couchbase
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2023-09-20
.\"    Manual: Couchbase Server Manual
.\"    Source: Couchbase Server 7.2.2-6401
.\"  Language: English
.\"
.TH "CBDOCLOADER" "1" "2023-09-20" "Couchbase Server 7.2.2\-6401" "Couchbase Server Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
cbdocloader \- (Deprecated) A utility to import sample buckets into Couchbase Server.
.SH "DESCRIPTION"
.sp
\f(CRcbdocloader\fP has been deprecated, please use \f(CRcbimport\fP with the
\f(CR\-\-format sample\fP flag instead.
.sp
The \f(CRcbdocloader\fP tool loads Couchbase sample datasets into Couchbase Server.
Sample datasets are zip files, provided by Couchbase, which contain documents and index definitions.
These datasets are intended to allow users to explore Couchbase features prior to loading their own datasets.
.sp
For Linux, the tool\(cqs location is \fI/opt/couchbase/bin/cbdocloader\fP; for Windows, \fIC:\(rsProgram Files\(rsCouchbase\(rsServer\(rsbin\(rscbdocloader\fP; and for Mac OS X, \fI/Applications/Couchbase Server.app/Contents/Resources/couchbase\-core/bin/cbdocloader\fP.
.SH "SYNTAX"
.sp
The syntax for \f(CRcbdocloader\fP is as follows:
.sp
.if n .RS 4
.nf
.fam C
cbdocloader \-\-cluster [hostname] \-\-username [username]
\-\-p [password] \-\-bucket [bucket\-name] \-\-bucket\-quota [quota]
\-\-dataset [path] \-\-thread [number] \-\-verbose
.fam
.fi
.if n .RE
.SH "OPTIONS"
.sp
Command options are as follows:
.TS
allbox tab(:);
lt lt.
T{
.sp
Option
T}:T{
.sp
Description
T}
T{
.sp
\f(CR\-h \-\-help\fP
T}:T{
.sp
Show this help message and exit.
T}
T{
.sp
\f(CR\-c [hostname], \-\-cluster [hostname]\fP
T}:T{
.sp
The hostname of one of the nodes in the cluster to load data into.
See the Host Formats section below for hostname specification details.
T}
T{
.sp
\f(CR\-u [username], \-\-user [username]\fP
T}:T{
.sp
The username for cluster authentication.
The user must have the appropriate privileges to create a bucket, write data, and create view, secondary index and full\-text index definitions.
This can be specified by means of the environment variable \f(CRCB_REST_USERNAME\fP.
T}
T{
.sp
\f(CR\-p [password], \-\-password [password]\fP
T}:T{
.sp
The password for cluster authentication.
The user must have the appropriate privileges to create a bucket, write data, and create view, secondary index and full\-text index definitions.
This can be specified by means of the environment variable \f(CRCB_REST_PASSWORD\fP.
T}
T{
.sp
\f(CR\-\-client\-cert [path]\fP
T}:T{
.sp
The path to a client certificate.
The path to a client certificate used to authenticate when connecting to a cluster. May be supplied with \f(CR\-\-client\-key\fP
as an alternative to the \f(CR\-\-username\fP and \f(CR\-\-password\fP flags.
T}
T{
.sp
\f(CR\-\-client\-key [path]\fP
T}:T{
.sp
The path to the client private key.
The path to the client private key whose public key is contained in the certificate provided to the \f(CR\-\-client\-cert\fP
flag. May be supplied with \f(CR\-\-client\-key\fP as an alternative to the \f(CR\-\-username\fP and \f(CR\-\-password\fP flags.
T}
T{
.sp
\f(CR\-m [quota], \-\-bucket\-quota [quota]\fP
T}:T{
.sp
The amount of memory to assign to the bucket.
If the bucket already exists, this parameter is ignored.
T}
T{
.sp
\f(CR\-d [path], \-\-dataset [path]\fP
T}:T{
.sp
The path of the dataset to be loaded.
The path can refer to either a zip file or a directory to load data from.
T}
T{
.sp
\f(CR\-t [number],\-\-threads [number]\fP
T}:T{
.sp
Specifies the number of concurrent clients to use when loading data.
Fewer clients means data loading will take longer, but with fewer cluster resources used.
More clients means faster data loading, but with higher cluster\-resource usage.
This parameter defaults to 1 if it is not specified.
This parameter is recommended not to be set to be higher than the number of CPUs on the machine where the command is being run.
T}
T{
.sp
\f(CR\-v,\-\-verbose\fP
T}:T{
.sp
Prints log messages to stdout.
This flag is useful for debugging errors in the data loading process.
T}
T{
.sp
\f(CR\-\-no\-ssl\-verify\fP
T}:T{
.sp
Skips the SSL verification phase. Specifying this flag will allow a
connection using SSL encryption, but will not verify the identity of the server
you connect to. You are vulnerable to a man\-in\-the\-middle attack if you use
this flag. Either this flag or the \-\-cacert flag must be specified when using
an SSL encrypted connection.
T}
T{
.sp
\f(CR\-\-cacert\fP
T}:T{
.sp
Specifies a CA certificate that will be used to verify the identity of the
server being connecting to. Either this flag or the \-\-no\-ssl\-verify flag must
be specified when using an SSL encrypted connection.
T}
.TE
.sp
.SH "HOST FORMATS"
.sp
When specifying a host/cluster for a command using the \f(CR\-c\fP/\f(CR\-\-cluster\fP flag, the following formats
are accepted:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttp://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://<srv>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://<srv>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR<addr>:<port>,<addr>:<port>\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR<scheme>://<addr>:<port>,<addr>:<port>\fP
.RE
.sp
The \f(CR<port>\fP portion of the host format may be omitted, in which case the default port will be used
for the scheme provided. For example, \f(CRhttp://\fP and \f(CRcouchbase://\fP will both default to 8091 where
\f(CRhttps://\fP and \f(CRcouchbases://\fP will default to 18091. When connecting to a host/cluster using a
non\-default port, the \f(CR<port>\fP portion of the host format must be specified.
.SS "Connection Strings (Multiple nodes)"
.sp
The \f(CR\-c\fP/\f(CR\-\-cluster\fP flag accepts multiple nodes in the format of a connection string; this is a
comma separated list of \f(CR<addr>:<port>\fP strings where \f(CR<scheme>\fP only needs to be specified once.
The main advantage of supplying multiple hosts is that in the event of a failure, the next host in
the list will be used.
.sp
For example, all of the following are valid connection strings:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRlocalhost,[::1]\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR10.0.0.1,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttp://10.0.0.1,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://10.0.0.1:12345,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://10.0.0.1,10.0.0.2\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://10.0.0.1:12345,10.0.0.2:12345\fP
.RE
.SS "SRV Records"
.sp
The \f(CR\-c\fP/\f(CR\-\-cluster\fP flag accepts DNS SRV records in place of a host/cluster address where the SRV
record will be resolved into a valid connection string. There are a couple of rules which must be
followed when supplying an SRV record which are as follows:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \f(CR<scheme>\fP portion must be either \f(CRcouchbase://\fP or \f(CRcouchbases://\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \f(CR<srv>\fP portion should be a hostname with no port
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \f(CR<srv>\fP portion must not be a valid IP address
.RE
.sp
For example, all of the following are valid connection string using an SRV record:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbase://hostname\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRcouchbases://hostname\fP
.RE
.SS "Alternate Addressing (CAO/K8S)"
.sp
Users of the CAO (Couchbase Autonomous Operator) or K8S may need to supply the
\f(CRnetwork=external\fP query parameter to force connection via the defined
alternate addressing.
.sp
For example, the following are valid connection strings:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://10.0.0.1:12345,10.0.0.2?network=default\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRhttps://10.0.0.1:12345,10.0.0.2?network=external\fP
.RE
.SH "CERTIFICATE AUTHENTICATION (MTLS AUTHENTICATION)"
.sp
This tool supports authenticating against a Couchbase Cluster by using certificate based authentication (mTLS
authentication). To use certificate based authentication a certificate/key must be supplied, there a currently
multiple ways this may be done.
.SS "PEM ENCODED CERTIFICATE/KEY"
.sp
An unencrypted PEM encoded certificate/key may be supplied by using:
\- \f(CR\-\-client\-cert <path>\fP
\- \f(CR\-\-client\-key <path>\fP
.sp
The file passed to \f(CR\-\-client\-cert\fP must contain the client certificate, and an optional chain required to authenticate
the client certificate.
.sp
The file passed to \f(CR\-\-client\-key\fP must contain at most one private key, the key can be in one of the following formats:
\- PKCS#1
\- PKCS#8
\- EC
.sp
Currently, only the following key types are supported:
\- RSA
\- ECDSA
\- ED25519
.SS "PEM ENCODED CERTIFICATE/PEM OR DER ENCRYPTED PKCS#8 KEY"
.sp
An encrypted PKCS#8 formatted key may be provided using:
\- \f(CR\-\-client\-cert <path>\fP
\- \f(CR\-\-client\-key <path>\fP
\- \f(CR\-\-client\-key\-password <password>\fP
.sp
The file passed to \f(CR\-\-client\-cert\fP must contain the client certificate, and an optional chain required to authenticate
the client certificate.
.sp
Currently, only the following key types are supported:
\- RSA
\- ECDSA
\- ED25519
.SS "ENCRYPTED PKCS#12 CERTIFICATE/KEY"
.sp
An encrypted PKCS#12 certificate/key may be provided using:
\- \f(CR\-\-client\-cert <path>\fP
\- \f(CR\-\-client\-cert\-password <password>\fP
.sp
The file passed to \f(CR\-\-client\-cert\fP must contain the client certificate and exactly one private key. It may also contain
the chain required to authenticate the client certificate.
.sp
Currently, only the following key types are supported:
\- RSA
\- ECDSA
\- ED25519
.SH "OPERATIONS DURING MAJOR CLUSTER CONFIGURATION CHANGES"
.sp
Operations (commands or sub\-commands) which connect to a cluster are not
supported during major cluster configuration changes.
.sp
For example, performing an import/export, making a backup or performing a
restore whilst changing the TLS configuration/security settings is unsupported.
.sp
These types of changes (e.g. changing the TLS mode to strict) are not expected
to be time consuming so it\(cqs generally expected that operations should be
started after completing the configuration change.
.sp
Please note that this does not include rebalances; operations may be performed
during a rebalance. The reason for this distinction, is that major cluster
configuration changes are generally quick, whilst rebalances for large data
sets may be time consuming.
.SH "EXAMPLES"
.sp
To load the dataset \f(CRtravel\-sample.zip\fP, which is located in \fI/opt/couchbase/samples/\fP, into a bucket with a memory quota of 1024MB, run the following command.
.sp
.if n .RS 4
.nf
.fam C
cbdocloader \-c couchbase://127.0.0.1 \-u Administrator \(rs
\-p password \-m 1024 \-b travel\-sample \(rs
\-d /opt/couchbase/samples/travel\-sample.zip
.fam
.fi
.if n .RE
.sp
To increase the parallelism of data\-loading, use the \fIthreads\fP option.
In the example below, 4 threads are specified.
.sp
.if n .RS 4
.nf
.fam C
cbdocloader \-c couchbase://127.0.0.1 \-u Administrator \(rs
\-p password \-m 1024 \-b travel\-sample \(rs
\-d /opt/couchbase/samples/travel\-sample.zip \-t 4
.fam
.fi
.if n .RE
.sp
The \f(CRcbdocloader\fP command can also be used to load data from a folder.
The folder must contain files that correspond to the samples format.
See the Sample Data Format section below, for more information.
The following example show to load data from folder \fI/home/alice/census\-sample\fP:
.sp
.if n .RS 4
.nf
.fam C
cbdocloader \-c couchbase://127.0.0.1 \-u Administrator \(rs
\-p password \-m 1024 \-b census\-sample \-d /home/alice/census\-sample
.fam
.fi
.if n .RE
.SH "SAMPLE DATA FORMAT"
.sp
The \f(CRcbdocloader\fP command is used to load data from zip files or folders that correspond to the \fICouchbase sample data format\fP.
This is exemplified as follows:
.sp
.if n .RS 4
.nf
.fam C
+ sample_folder
  + design_docs
    indexes.json
    design_doc.json
  + docs
    document1.json
    document2.json
    document3.json
    document4.json
.fam
.fi
.if n .RE
.sp
The top level directory can be given any name and will always contain two folders.
The \f(CRdesign_docs\fP folder is where index definitions are kept.
This folder will contain zero or more JSON files that contain the various indexes that should be created when the sample dataset is loaded.
Global Secondary Indexes (GSI) should always be in a file named \f(CRindexes.json\fP.
Below is an example of the format for defining GSI indexes.
.sp
.if n .RS 4
.nf
.fam C
{
 "statements": [
   {
     "statement": "CREATE PRIMARY INDEX on `bucket1`",
     "args": null
   },
   {
     "statement": "CREATE INDEX by_type on `bucket1`(name) WHERE _type=\*(AqUser\*(Aq"
     "args": null
   }
 ]
}
.fam
.fi
.if n .RE
.sp
GSI indexes are defined as a JSON document where each index definition is contained in a list called \f(CRstatements\fP.
Each element in the list is an object that contains two keys.
The \f(CRstatement\fP key contains the actual index definition, and the \f(CRargs\fP key is used if the statement contains any positional arguments.
.sp
All other files in the \f(CRdesign_docs\fP folder are used to define view design documents, and each design document should be put
into a separate file.
These files can be named anything, but should always have the \f(CR.json\fP file extension.
Below is an example of a view design document definition.
.sp
.if n .RS 4
.nf
.fam C
{
   "_id": "_design/players"
   "views": {
     "total_experience": {
       "map": "function(doc,meta){if(doc.jsonType ==
       "reduce": "_sum"
     },
     "player_list": {
       "map": "function (doc, meta){if(doc.jsonType ==
     }
   }
 }
.fam
.fi
.if n .RE
.sp
In the document above, the \f(CR_id\fP field is used to name the design document.
This name should always be prefixed with \f(CR_design/\fP.
The other field in the top level of the document is the \f(CRviews\fP field.
This field contains a map of view definitions.
The key for each element in the map is the name of the view.
Each view must contain a \f(CRmap\fP element that defines the map function, and may also contain an optional \f(CRreduce\fP element that defines the reduce function.
.sp
View design documents support map\-reduce views as well as spatial views.
Below is an example of a spatial view definition.
Spatial views follow similar rules as the map\-reduce views above.
.sp
.if n .RS 4
.nf
.fam C
 {
   "_id": "_design/spatial"
   "spatial": {
                 "position": "<spatial view function definition>",
                "location": "<spatial view function definition>"
   }
 }
.fam
.fi
.if n .RE
.sp
Note that spatial views only use a single function to define the index.
As a result this function is defined as the value of the spatial views name.
.sp
The other folder at the top level directory of a sample data folder is the \f(CRdocs\fP folder.
This folder will contain all of the documents to load into Couchbase.
Each document in this folder is contained in a separate file and each file should contain a single JSON document.
The key name for the document will be the name of the file.
Each file should also have a \f(CR.json\fP file extension which will be removed from the key name when the data is loaded.
Since each document to be loaded is in a separate file, there can potentially be many files.
The docs folder allows subfolders to help categorize documents.
.SH "AUTHOR"
.sp
Couchbase