# pyline disable=C0303, C0325

class Config:
    def __init__(self, my_json):
        self.my_json = my_json
        self.weeks_to_keep = self.my_json['weeks_to_keep']
        self.archive = self.my_json['archive']
        self.specify_repo = self.my_json['specify_repo']
        self.repo = self.my_json['repo']
        self.exclude_buckets = self.my_json['exclude_buckets']
        self.include_buckets = self.my_json['include_buckets']
        self.disable_bucket_config = self.my_json['disable_bucket_config']
        self.exclude_bucket_list = self.my_json['exclude_bucket_list']
        self.include_bucket_list = self.my_json['include_bucket_list']
        self.disable_views = self.my_json['disable_views']
        self.disable_gsi_indexes = self.my_json['disable_gsi_indexes']
        self.disable_fts_indexes = self.my_json['disable_fts_indexes']
        self.disable_fts_alias = self.my_json['disable_fts_alias']
        self.disable_data = self.my_json['disable_data']
        self.disable_analytics = self.my_json['disable_analytics']
        self.disable_eventing = self.my_json['disable_eventing']
        self.vbucket_filter = self.my_json['vbucket_filter']
        self.vbucket_filter_list = self.my_json['vbucket_filter_list']
        self.cb_version = self.my_json['cb_version']
        self.username = self.my_json['username']
        self.password = self.my_json['password']
        self.value_compression = self.my_json['value_compression']
        self.threads = self.my_json['threads']
        self.no_progress_bar = self.my_json['no_progress_bar']
        self.hostname = self.my_json['hostname']
        self.port = self.my_json['port']
