apiVersion: batch/v1
kind: Job
metadata:
  name: vxingest-pipeline-orchestrator
  namespace: vxingest-dev
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: vxingest-orchestrator
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: orchestrator
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: vxingest-orchestrator-params
          command:
            - /bin/bash
            - /scripts/orchestrate.sh
          volumeMounts:
            - name: orchestrator-script
              mountPath: /scripts
      volumes:
        - name: orchestrator-script
          configMap:
            name: vxingest-orchestrator-script
            defaultMode: 0755
