apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vxingest-dev

resources:
  - namespace.yaml
  - sa-orchestrator.yaml
  - role-orchestrator.yaml
  - rolebinding-orchestrator.yaml
  - configmap-orchestrator-params.yaml
  - configmap-orchestrator-script.yaml
  - secret-credentials.template.yaml
  - secret-cacert.template.yaml
  - pvc-data.yaml
  - pvc-public.yaml
  - job-orchestrator.yaml
  - job-ingest.yaml
  - job-import.yaml
  - job-meta-update.yaml
