apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vxingest-public-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # Uncomment and set for your cluster:
  # storageClassName: standard
