apiVersion: v1
kind: Secret
metadata:
  name: vxingest-cacert
type: Opaque
stringData:
  cacert.pem: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_YOUR_CAPELLA_CA_CERTIFICATE
    -----END CERTIFICATE-----
