apiVersion: v1
kind: Secret
metadata:
  name: vxingest-credentials
type: Opaque
stringData:
  credentials.yaml: |
    cb_host: "couchbase://your-host"
    cb_user: "your-user"
    cb_password: "your-password"
    cb_bucket: "vxdata"
    cb_scope: "_default"
    cb_collection: "METAR"
    # Optional for long-running operations:
    # cb_timeout_seconds: 7200
