name: ADR Accepted
on:
  issues:
    types:
      - closed

jobs:
  main:
    name: Create ADR
    runs-on: ubuntu-latest

    # Only run this workflow if the closed issue has the "ADR: accepted" label
    if: "${{ contains(github.event.issue.labels.*.name, 'ADR: accepted') }}"

    steps:
      - name: checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: create the ADR
        id: create-adr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 .github/jobs/create_adr.py \
            --repo ${{ github.repository }} \
            --issue ${{ github.event.issue.number }} \
            --adr-prefix adr \
            --base-path docs/decisions/architecture

      - name: branch, commit, and open PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="adr-auto-${{ github.event.issue.number }}"
          git config --global user.email "mats.gsl@noaa.gov"
          git config --global user.name "GSL verification team ADR automation"
          # Check if the branch already exists, exit-code 2 means it doesn't, and that creating a new branch is safe.
          set +e # override set -e since we're hoping for an exit code
          git ls-remote --exit-code --heads origin refs/heads/$BRANCH > /dev/null
          branch_exists=$?
          set -e
          if [ $branch_exists -eq 2 ]; then
            git checkout -b $BRANCH
            git add docs/decisions/architecture/*.md
            git commit -m "Add ADR for: ${{ github.event.issue.title }}"
            git push -f origin $BRANCH
            gh pr create \
                --title "Add ADR for #${{ github.event.issue.number }} to the repo" \
                --body "This pull request was opened automatically because #${{ github.event.issue.number }} was closed after being marked as an approved ADR. It contains a markdown file capturing the ADR body at the time the issue was closed. Please verify that the markdown is correct before merging!" || true
          else
            echo "Error - Branch $BRANCH already exists, PR will need to be created manually.

            # Create a step summary
            echo "# Error" >> $GITHUB_STEP_SUMMARY
            echo "Branch $BRANCH already exists, PR will need to be created manually. Directions are below. Exiting." >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            echo "python3 .github/jobs/create_adr.py \\" >> $GITHUB_STEP_SUMMARY
            echo "  --repo ${{ github.repository }} \\" >> $GITHUB_STEP_SUMMARY
            echo "  --issue ${{ github.event.issue.number }} \\" >> $GITHUB_STEP_SUMMARY
            echo "  --adr-prefix=adr \\" >> $GITHUB_STEP_SUMMARY
            echo "  --base-path docs/decisions/architecture" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
